### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by rayfoss** [alessandrofrancesconi/gimp-plugin-bimp#101]
![screenshot from 2016-01-05 13-03-47](https://cloud.githubusercontent.com/assets/876076/12123085/ce1ffd22-b3ac-11e5-8f29-0b85d45605b2.png)
![screenshot from 2016-01-05 13-03-35](https://cloud.githubusercontent.com/assets/876076/12123086/ce21709e-b3ac-11e5-91d1-d7aa10feddd8.png)

It's a bit difficult to read on a 2x device_pixel_ratio on Gnome Shell 3.18.3

**Comment by alessandrofrancesconi** [comment]
Is this problem happening only on BIMP or also on other plugins (especially the ones made by other devs outside the GIMP team)?

**Comment by Reyncor** [comment]
Tried installing Wavelet denoise, no issue.
![screenshot from 2016-01-08 11-56-26](https://cloud.githubusercontent.com/assets/876076/12171338/f51efafc-b4fd-11e5-8ee9-027e523d7a6e.png)

**Comment by schumaml** [comment]
I guess the plug-in has to declare that it supports HiDPI, i.e. has to be linked with a suitable manifest resource. See https://git.gnome.org/browse/gimp/tree/build/windows for how to do this, i.e. the gimp-plug-ins.rc.in and gimp.manifest files there.

**Comment by KrasnayaPloshchad** [comment]
What happened if you update GIMP to 2.10?

**Comment by rayfoss** [comment]
gimp 2.8.22 on Fedora 28. I suppose a good way to test all this is to set the gnome pixe ratio to 2

`$ gsettings set org.gnome.desktop.interface scaling-factor 2`

![screenshot from 2018-06-02 17-01-13](https://user-images.githubusercontent.com/876076/40881194-94091990-6686-11e8-830e-d64b410a09a6.png)
