### ISSUE TITLE
setting import svg parameters

### ISSUE THREAD

**Issue by DavidBrenner3** [alessandrofrancesconi/gimp-plugin-bimp#106]
Hi.

Great plugin.
Thank you very much.

The plugin is loading svg files at their default width and height.
Is there a way to set the import svg parameters (width, height, ...) for every svg file or for all svg files in the same time?
If there isn't, would you consider implementing it in a future version?

Thank you in advance.

Best regards,
David

**Comment by alessandrofrancesconi** [comment]
Currently, I'm not considering this because it will lengthen all the batch process, that must remain simple and quick to use. Surely, I won't go for the possibility to set svg parameters for _every_ image file, this is totally out of scope.
