### ISSUE TITLE
a few suggestions + bugs

### ISSUE THREAD

**Issue by DavidBrenner3** [alessandrofrancesconi/gimp-plugin-bimp#107]
Hi.

1. How about using the properties of the input image as parameters for the procedures/plugins?
For example the user may want to draw a shadow with the same position/size on screen (inch/cm not pixels) in any image resolution.
So the position/size of the shadow could be: DefaultValue * CurImgRes / RefImgRes.
Or using the index of the file or part of the file name.

2. I noticed that some simple functions (like Alpha to selection, Grow/Shrink selection) are missing. They are important too, not just the plugins. Yes, they are visual modifications but sometimes are needed to achieve the result. And I know they can be used in batch operations because are already been used by most of the plugins already implemented in Bimp.
For example now I'm trying to create a Bump map by growing some objects (delimited by alpha). And I can't find a way (in Bimp, in Gimp I can) :(

3. Also some parameters are missing. For example the Bump Map image used for the bump map plugin.
This image will be loaded from a file but you might consider implementing the use of a temp image obtained in previous operations.

4. It should load the default values for parameters in the procedures/plugins used, instead of asking the user to set all of them.

5. The user should be able to change the order in which procedures/plugins are used. Maybe even to insert a procedure/plugin.

6. It should remember the last folders used (for input and output) and/or the last set used.

7. How about fixing the click on the link in About - if I try it the plugin always crashes.

8. You could turn off Undo. This way it will be faster and it will take less resources (RAM).

9. Found another bug: I added some parameters to a plugin, Bimp refused to save the new parameters into the set save file until I manually modified the file adding the extra parameters and setting the updated value for num_params..

10. It's very hard to stop the processing. I know that is not very used, but still...
And many users click more than once hoping that it will "catch" at least one of them. But the button becomes "Apply" and start processing the files again. You can clear the mouse/keyboard buffer after the user clicks on Stop.

Best regards,
David

**Comment by alessandrofrancesconi** [comment]
Hello David,
first of all, thanks for this rich contribution. There are some interesting ideas and I think that the best way will be to split them in single GitHub issues. I'll reply to each of them, I'll open the single issues when I found something valid, then I'll close this.

> 1) How about using the properties of the input image as parameters for the procedures/plugins?
For example the user may want to draw a shadow with the same position/size on screen (inch/cm not pixels) in any image resolution.

This first idea is good but, without great efforts, is technically impossible to implement. It needs a way to first extract a set of image properties in variables and keywords (e.g. "CurImgRes"), then the ability to inject this keywords inside the GTK+ and parse them during the processing. The first problem that comes to my mind is that most of the input elements only accepts numbers, not text.

> 2) I noticed that some simple functions (like Alpha to selection, Grow/Shrink selection) are missing. They are important too, not just the plugins. Yes, they are visual modifications but sometimes are needed to achieve the result. And I know they can be used in batch operations because are already been used by most of the plugins already implemented in Bimp.

This is related to how BIMP and the GIMP plugins environment work. All the manipulations you add to the BIMP list are totally independent from each other. For example, if I add a "selection step" before a "colorize step", the selection will work and return a selection ID, but once the procedure finishes this data is cleared and cannot be passed in any way to the colorize step.
This is why I explicitly filter selection plugins from the "Other GIMP procedures" list: they are not compatible with how BIMP as been conceived.

> 3) Also some parameters are missing. For example the Bump Map image used for the bump map plugin.
This image will be loaded from a file but you might consider implementing the use of a temp image obtained in previous operations.

Let's see this bump map plugin: it contains two drawable parameters, one is your image, the other one is a map. Internally on GIMP, a "drawable" is a pointer to an image loaded in memory. That means that, when you add this plugin as a BIMP step, you are forced to specify a pointer to an image that you have loaded beforehand. This is easy when you write low-level scripts, but at user-level this operation is really hard to implement. I'm trying to keep the BIMP interface as simple as possible and this feature will risk to confuse a tipical user. 
Anyway, feel free to think about how can it be implemented if you have deeper knowledge of the GIMP environment, or ask someone if interested in this task.

> 4) It should load the default values for parameters in the procedures/plugins used, instead of asking the user to set all of them.

The response is simple: there are no default parameters for plugins. When populating the list, BIMP asks to GIMP some information like name, description and the set of parameters, but there are no chances to get default values.

> 5) The user should be able to change the order in which procedures/plugins are used. Maybe even to insert a procedure/plugin.

This is good although it needs to rewrite the manipulations panel: #108

> 6) It should remember the last folders used (for input and output) and/or the last set used.

If you mean something to remember the paths between multiple BIMP sessions (open - exit - open), then, again, it will introduce too many complications in the code to enable a not critical feature. Where to store those data? On a file? On the registry (Windows only)? Moreover, this feature is already available in some form thanks to GTK+ and the "recently used" button when you open a path selection dialog.

> 7) How about fixing the click on the link in About - if I try it the plugin always crashes.

This is a problem of your installation. When clicking, GTK+ searches the path of the default browser in your operative system, then it opens it. On Linux this should work fine, while on Windows I sometimes saw an error dialog that says that it cannot find the browser, but no crashes. It could be a GTK+ bug so you'd better open a bug report on the official website: http://www.gtk.org/development.php

> 8) You could turn off Undo. This way it will be faster and it will take less resources (RAM).

This is interesting, I've never thought about it. #109

> 9) Found another bug: I added some parameters to a plugin, Bimp refused to save the new parameters into the set save file until I manually modified the file adding the extra parameters and setting the updated value for num_params..

I'll look for that: #110. Can you please provide some detailed steps to reproduce the bug?

> 10) It's very hard to stop the processing. I know that is not very used, but still...
And many users click more than once hoping that it will "catch" at least one of them. But the button becomes "Apply" and start processing the files again. You can clear the mouse/keyboard buffer after the user clicks on Stop.

First of all, users should not hope to stop the process by clicking the button more than once :smile: 
Anyway, I'll investigate the "mouse/keyboard buffer" thing.

Thank you for all.

**Comment by alessandrofrancesconi** [comment]
@DavidBrenner3 you should give me some feedback about #110
