### ISSUE TITLE
Download for El Capitan OS

### ISSUE THREAD

**Issue by aishaho** [alessandrofrancesconi/gimp-plugin-bimp#111]
Hey,

Looks like a great plugin, but I'm on El Capitan and a somewhat novice to GIMP. The Mac install you suggest doesn't have a version for El Capitan nor do I really want to download another version of GIMP so I tried looking at your source code to install it onto the version of GIMP I have (2.8.16) but I have no idea how to do that looking at the files. Any suggestions?

Thanks!

**Comment by alessandrofrancesconi** [comment]
Hello, in the latest version of the README you will find useful information to compile BIMP on Mac!
