### ISSUE TITLE
GIMP installation was not found error.

### ISSUE THREAD

**Issue by omero72** [alessandrofrancesconi/gimp-plugin-bimp#112]
Gimp-2.6 is installed on my WinXP Laptop at C:\Program Files\GIMP-2.0, but the installer says "GIMP installation was not found" Does it require a newer version of Gimp or expect Gimp to be installed on another path?

**Comment by alessandrofrancesconi** [comment]
Did you install GIMP using the official installer? The BIMP installer looks for a particular registry key added by the setup process. You try to:
- reinstall GIMP 2.6
- update to GIMP 2.8, again using the Windows installer here https://download.gimp.org/mirror/pub/gimp/v2.8/windows/gimp-2.8.16-setup-2.exe

**Comment by omero72** [comment]
updating to GIMP 2.8 is out of question because I find it's UI and usability bad & different from 2.6 so I don't use it. 
I think reinstalling will do no good because it will be same 2.6 installer. I think editing the Windows Registry manually is the most useful option for me. I'll give it a try.

**Comment by alessandrofrancesconi** [comment]
The BIMP's installer looks for GIMP's directory at this point: https://github.com/alessandrofrancesconi/gimp-plugin-bimp/blob/master/nsis/win32_install.nsi#L44

Please let me know
