### ISSUE TITLE
Feature Request: xBRZ Texture Filter

### ISSUE THREAD

**Issue by waltzz92** [alessandrofrancesconi/gimp-plugin-bimp#116]
Hi, thanks for the BIMP plugin. I have a request for a future update. Could you please implement the xBRZ filter. It would be very beneficial to upscale a folder full of pictures. Here is the link to the filter's source:

https://sourceforge.net/projects/xbrz/files/xBRZ/

Thanks.

**Comment by alessandrofrancesconi** [comment]
Hello, 
although interesting, your request is out of the main goals of BIMP plugin. You are asking to create a whole new plugin that implements the xBRZ filter, not a new feature for BIMP.
First of all, you should look around and check if such filter is already available for GIMP. If not, well, someone should make it. After that, you can try to call it from BIMP.
Anyway it would be an interesting plugin to create so I may consider the idea to work on it... but not today ;)
