### ISSUE TITLE
Bimp plugin not open

### ISSUE THREAD

**Issue by Tekhivez** [alessandrofrancesconi/gimp-plugin-bimp#119]
Just install Gimp 2.8.16 tonight and I install Bimp just after.

After installing Bimp, I got a error message saying that bimp.exe didn't start properly 
(0xc000007b). The application will be close.

Gimp continu to open and I don't see bimp add-on File menu.

I running them under Win 7.

Anything I can do to fix it ?

Thank

Eric

**Comment by alessandrofrancesconi** [comment]
Would you try to install the stand-alone version of the GTK+ engine? Download it from here: https://sourceforge.net/projects/gtk-win/files/latest/download?source=files

**Comment by Tekhivez** [comment]
Thank, it work now. I Try a few time, finally I uninstall everything and install back GIMP and full GTK and finish with Bimp installation
