### ISSUE TITLE
Wavelet Denoise has no editable parameters

### ISSUE THREAD

**Issue by waltzz92** [alessandrofrancesconi/gimp-plugin-bimp#120]
Hi, I noticed that BIMP does not have editable parameters for plug-in-wavelet-denoise. Would it be possible to choose the channel, threshold, and softness level for the plugin?

**Comment by alessandrofrancesconi** [comment]
This is because the developer didn't decide to make parameters editable from outside the plugin's GUI.
BIMP can't do nothing about that, so the think you can do is to ask the author itself ;)
