### ISSUE TITLE
Instructions 

### ISSUE THREAD

**Issue by chrisatbest** [alessandrofrancesconi/gimp-plugin-bimp#125]
Extract the archive containing the BIMP's sources and get into the extracted folder with cd

-the name of the folder is libgimp2.0-dev or  libpcre3-dev ?

-the directory name is ?

**Comment by alessandrofrancesconi** [comment]
libgimp2.0-dev and libpcre3-dev are not folders but libraries that you've previously installed with `sudo apt-get install libgimp2.0-dev libpcre3-dev`.
In that line I'm just saying that you have to extract the BIMP archive in a folder, then enter in it.

**Comment by chrisatbest** [comment]
i did that . and installed it . but after that what do i do?

**Comment by chrisatbest** [comment]
where is the BIMP archive

**Comment by alessandrofrancesconi** [comment]
The last thing you have to do is to launch `make && make install` from the extracted folder. If no error occurred, you can open GIMP and you will find "Batch Image Manipulation..." in the "File" menu.

**Comment by chrisatbest** [comment]
make && make install . ask where the folder is . which was my first question .   what is name of the folder and directory

**Comment by alessandrofrancesconi** [comment]
I have to be honest, I can't understand really much what you are asking here... What's the meaning of "ask where the folder is"? Is there an error when you launch `make && make install`? If so, please copy & paste it here.
Otherwise, well, explain it more clearly.

**Comment by chrisatbest** [comment]
make: *** No targets specified and no makefile found.  Stop.

**Comment by alessandrofrancesconi** [comment]
Great, that's because you are not launching `make` from the right location. In plain words, you have to launch that command, from a terminal, from the same location where the Makefile is.

So let's say you extracted gimp-plugin-bimp.zip (or whatever) into `/home/me/downloads/bimp`. In this folder you will find README.md, LICENSE... and most importantly Makefile. Open a terminal here and call `make && make install`.

**Comment by chrisatbest** [comment]
so apt-get install libgimp2.0-dev libpcre3-dev. have nothing to do with make && make install it but to the /gimp-plugin-bimp-1.17

**Comment by alessandrofrancesconi** [comment]
libgimp2.0-dev and libpcre3-dev are *dependencies*. If you don't install them before, make will not work.

**Comment by chrisatbest** [comment]
i thought the  ibgimp2.0-dev libpcre3-dev where the thing to make && make install but now i under stand that they where dependency.

maybe if you change the line from 

Extract the archive containing the BIMP's sources and get into the extracted folder with cd. Then:

to

Extract the download archive /gimp-plugin-bimp- containing the BIMP's sources and get into the extracted folder with cd. Then:

Thanks Alessandro  or your help will see if I can get it to work 
chris

**Comment by alessandrofrancesconi** [comment]
Any news? Did you manage to run BIMP?

**Comment by chrisatbest** [comment]
i did install it but cant find it in the plug-in-browser

**Comment by alessandrofrancesconi** [comment]
As well as in "File" menu?

**Comment by chrisatbest** [comment]
just found it is plug-in-browser but can not see it in gimp menus

**Comment by chrisatbest** [comment]
-filters
-batch
all i get is 
david's batch processor

**Comment by alessandrofrancesconi** [comment]
You don't have to search into the Filters menu. As I said, BIMP is in the **File** menu, the first one on the left. You will find “Batch Image Manipulation…” item there.

**Comment by chrisatbest** [comment]
there it is. 

IN the File menu help

thanks for all your help
