### ISSUE TITLE
v1.17 Win32 installer does not detect GIMP installation

### ISSUE THREAD

**Issue by redbaronMIT** [alessandrofrancesconi/gimp-plugin-bimp#131]
When I run the windows installer, I receive the message:  "GIMP installation not found. Please install GIMP..." However, I do have GIMP installed.

GIMP directory: C:\Program Files (x86)\GIMP-2.0
Version: GIMP 2.6.11

![image](https://cloud.githubusercontent.com/assets/5309923/19626959/f0086b56-990a-11e6-919e-3920ccb022cd.png)

**Comment by Brianckeith** [comment]
I can install BIMP on the latest release of 2.8. I cannot install on 2.6.12 or 2.6.7. It appears to be related to the version that it's looking for, which is only 2.8?
