### ISSUE TITLE
the recipe is a mistake for the purpose of «make»

### ISSUE THREAD

**Issue by garilla22** [alessandrofrancesconi/gimp-plugin-bimp#135]
I installed packages libgimp2.0-dev libpcre3-dev and it gave me just such a mistake:

> root#:/home/admin/Downloads/gimp-plugin-bimp-master make
> make: gimptool-2.0: Command not found
> which gimptool-2.0 && which pcre-config && \
> gcc -o ./bin/bimp -Wall -O2 -Wno-unused-variable -Wno-pointer-sign -Wno-parentheses src/*.c src/manipulation-gui/*.c   -lpcre -lm -DGIMP_DISABLE_DEPRECATED
> Makefile:7: the recipe is a mistake for the purpose of «make»
> make: *** [make] Error 1

**Comment by alessandrofrancesconi** [comment]
I see `gimptool-2.0: Command not found`
Are you sure that you correctly installed `libgimp2.0-dev`? What's your distribution?

**Comment by garilla22** [comment]
My distribution
> Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
In search of this program it is
> dpkg --list|egrep libgimp
> ii  libgimp2.0                            2.8.14-1+deb8u1                      amd64        Libraries for the GNU Image Manipulation Program

**Comment by alessandrofrancesconi** [comment]
You have correctly installed libgimp2.0, but not libgimp2.0-dev (that's the version that includes gimptool-2.0): https://packages.debian.org/jessie/libgimp2.0-dev

Just type `sudo apt-get install libgimp2.0-dev`
