### ISSUE TITLE
Colour Balance not applied on every photo in batch

### ISSUE THREAD

**Issue by coinrese** [alessandrofrancesconi/gimp-plugin-bimp#136]
Hi,
I tried to batch edit around 25 photos with mixed success. All edits were applied correctly apart from the colour balance edits, which were only applied to around 5-6 of the images.
Any ideas why this might be?

Best Wishes
Matt

**Comment by alessandrofrancesconi** [comment]
Can you provide more details about the "color balance" step your are talking about?

**Comment by coinrese** [comment]
So I did the colour balance in 3 steps.

Step 1 Shadow
Cyan-Red.  31
Magenta-Green.  15
Yellow-Blue.  -10

Step 2 Midtones
Cyan-Red.  3
Magenta-Green.  -5
Yellow-Blue.  -24

Step 3 Highlights
Cyan-Red.  -2
Magenta-Green.  -3
Yellow-Blue.  -96

**Comment by alessandrofrancesconi** [comment]
Color balance works only on RGB images. Maybe some of them are Grayscale or even Indexed?

**Comment by coinrese** [comment]
Hi Alessandro,

I have realised where i was going wrong. I was batch editing .xcf files and in the majority of the files i had an inverted selection meaning the subject of the image was not selected, hence the colour balance wasn't applied as expected.
Apologies.
Matt
