### ISSUE TITLE
JPEG2000 support

### ISSUE THREAD

**Issue by alessandrofrancesconi** [alessandrofrancesconi/gimp-plugin-bimp#138]
Add possibility to open and save JPEG2000 images

**Comment by KrasnayaPloshchad** [comment]
GIMP 2.10 got support natively.

**Comment by alessandrofrancesconi** [comment]
Latest version [v2.0](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/releases/tag/v2.0) should fix this issue. Please give it a try!
