### ISSUE TITLE
On GIMP start-up it asks to uninstall BIMP

### ISSUE THREAD

**Issue by fuaim** [alessandrofrancesconi/gimp-plugin-bimp#140]
Used 'gimp-plugin-bimp_win32.exe' to install BIMP1.18 on GIMP 2.8.8.

Every time I start-up GIMP it asks to uninstall BIMP. Problem is that GIMP runs:
C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\bimp-uninstall.exe

I removed this file and the issue is solved.

PS: Create tool by the way 👍

**Comment by alessandrofrancesconi** [comment]
This is weird because:
* At startup, GIMP scans the content of the plug-ins directory and looks for valid plugins. Of course it reads "bimp-uninstall.exe" but being not a real plugin it should skip it.
* I can't reproduce it ;) As stated in the first point, this executable is ignored by GIMP.

**Comment by egyres** [comment]
Having the same issue using BIMP1.18 with GIMP 2.8.20 on Win 7.
The workaround mentioned by fuaim works.

**Comment by alessandrofrancesconi** [comment]
Ok, thank

**Comment by alessandrofrancesconi** [comment]
Found the reason: it happens when GIMP is executed with Administrator privileges.
I'll work on the installer to put that exe in another location.

**Comment by farance** [comment]
Hi, I am having the same problem too.  I am running Windows 7 and, unlike XP where I am an Administrator, but access/create things under my own user name (as verified by cygwin's "ls -l") yet have Administrator privileges, it appears that on Windows 7, as an Administrator (even though I am signed in under by own account), I create/execute programs as if I had signed in under Administrator.  I don't know if this is related to this problem.  Here is an article on the topic:

https://serverfault.com/questions/19311/file-ownership-for-new-files-with-administrator-why-is-it-giving-ownership-to

**Comment by alessandrofrancesconi** [comment]
The installer has been updated without increasing the version number. Try it now: https://github.com/alessandrofrancesconi/gimp-plugin-bimp/releases/download/v1.18/gimp-plugin-bimp_win32.exe
