### ISSUE TITLE
XPM image support.

### ISSUE THREAD

**Issue by bmustiata** [alessandrofrancesconi/gimp-plugin-bimp#141]
Hi Alessandro, great plugin!

It would be great if you can add the XPM support, since a lot of themes icons in Linux use this format for storage, and batch processing them to change the colors would be great :).

**Comment by alessandrofrancesconi** [comment]
Latest version [v2.0](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/releases/tag/v2.0) should fix this issue. Please give it a try!
