### ISSUE TITLE
Record sequence of modifications

### ISSUE THREAD

**Issue by billhat** [alessandrofrancesconi/gimp-plugin-bimp#144]
Can be recorded a modification sequence to avoid having to reprogram the type of processing ?
Example "treatment of negative color = Crop, invert, Gaussian blur, record JPG...
An other point : if I want to save as JPG, I've not an access to the different options.

**Comment by billhat** [comment]
Beginner with Bimp, I was looking for the record option and don't see it first on the drop-down list
So, No problem for recording actions, My post is **solved** except for the  blur-gaus, 
I don't find how do it !

**Comment by alessandrofrancesconi** [comment]
You should clarify your question:

> if I want to save as JPG, I've not an access to the different options.

You want to add a "Change Format and Compression" step with JPEG as output. In that window you will find the "Advanced params" dropdown.

> My post is solved except for the blur-gaus

As you have seen BIMP lets you save and restore a previously used set of manipulations. What's the problem with blur-gauss?

**Comment by billhat** [comment]
Thank' s for your quick answer.
About jpg it's OK.

With blur-gauss, In "Other process Gimp, I only find :
     plug-in-blur
     plug-in-mblur
     plug-in-mblur-inward
     script-fu-tile-blur
I would like use "blur-gauss selective" with radius 3 which give the 
best result for me.

Regards

**Comment by alessandrofrancesconi** [comment]
So you need to add the "plug-in-sel-gauss" procedure ;)

**Comment by billhat** [comment]
Tank's ! fantastic ! so it was just necessary  to know the name of all 
the plug-in !!!
I send you a "small" donate.

**Comment by alessandrofrancesconi** [comment]
Thank you! 👍
