### ISSUE TITLE
Installation permission

### ISSUE THREAD

**Issue by MartensPh** [alessandrofrancesconi/gimp-plugin-bimp#146]
Hello,

I tried to install the newest version of plugin under restricted user on Windows and the plugin forced me to install some dll in the C:\Windows\System32 directory what is forbidden in our company.  I didn't install that dll and interestingly the plugin is working, but everytime when I start the GIMP, the software ask me to uninstall the plugin and everytime I have to cancel that. That is annoying :-).

**Comment by alessandrofrancesconi** [comment]
This bug has already been resolved in #140 
It will be part of the next release
