### ISSUE TITLE
The message "remove batch" appear on Gimp 

### ISSUE THREAD

**Issue by kisac** [alessandrofrancesconi/gimp-plugin-bimp#147]
Hi, 

Thanks for the soft, really useful :+1: 

I'm having an issue when i open gimp (latest version) the message "remove batch image" appear.

![image](https://user-images.githubusercontent.com/29857479/27785153-f9e7aabc-5fdc-11e7-85d1-9437fc985f2c.png)

Could you  please help me ?

**Comment by alessandrofrancesconi** [comment]
Duplicated and solved, it will be available in next relase ;)
https://github.com/alessandrofrancesconi/gimp-plugin-bimp/issues/140

**Comment by alessandrofrancesconi** [comment]
The installer has been updated without increasing the version number. Try it now: https://github.com/alessandrofrancesconi/gimp-plugin-bimp/releases/download/v1.18/gimp-plugin-bimp_win32.exe
