### ISSUE TITLE
BIMP not showing up in GIMP

### ISSUE THREAD

**Issue by nicholasiklim** [alessandrofrancesconi/gimp-plugin-bimp#150]
Hi. Thank you for this very useful plugin. However BIMP doesn't show in Gimp anymore after I updated to 2.8.22 or could be other causes , I don't know.  Would anyone be able to help??

I'm running win10 and already set Bimp to run as administrator. Tried uninstalling Gimp and manually deleted the folder in program files and reinstall everything, but still not working.

Thanks.

**Comment by alessandrofrancesconi** [comment]
Let's do some checks:

 - have you tried to reinstall BIMP using the latest version? Few days ago the installer has been updated to address #140 but without increasing the version number. So please re-download this: https://github.com/alessandrofrancesconi/gimp-plugin-bimp/releases/download/v1.18/gimp-plugin-bimp_win32.exe
 - Please confirm that the folder `C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins` contains the file named `bimp.exe`.

**Comment by nicholasiklim** [comment]
Hmm.. wow!  replied by the author.  Tried the steps you advised but still not working. Ahh... but kept trying other ways . I disabled  real time protection and firewall in Avira Free Antivirus, then only ran your installer, and now Bimp finally showed up in Gimp.  Antivirus the culprit.    Hm... but Thanks a dozen for your prompt reply and quick assistance.

The folder ... plug-ins contain bimp.exe .  But the file is date modified 21 Feb 2017.  still wonder why.

**Comment by alessandrofrancesconi** [comment]
> The folder ... plug-ins contain bimp.exe . But the file is date modified 21 Feb 2017. still wonder why.

This is because the bimp.exe file actually hasn't changed since that date. There have been updates on just the installer.
