### ISSUE TITLE
Ubuntu 16.04.3, BIMP 1.16 in Snap version of GIMP sees few fonts

### ISSUE THREAD

**Issue by RoyTheNewbie** [alessandrofrancesconi/gimp-plugin-bimp#151]
In Ubuntu 16.04.3 I have been using BIMP very happily with GIMP 2.8.16. Now I have installed the Snap version of GIMP 2.8.22 and I simply copied the BIMP plug-in , version 1.16, into the new program's plug-ins folder. BIMP does then work but a significant shortcoming is that the list of fonts available for making watermarks is much shorter. Now there is no Courier_New, Arial, etc. I have put a link in the (empty) fonts folder at snap/gimp/20/.gimp-2.8/fonts. GIMP "sees" these fonts but BIMP does not. Is this a bug or am I doing something wrong?

**Comment by alessandrofrancesconi** [comment]
This is related to system environment, not BIMP.
