### ISSUE TITLE
Req: Add Color Modes

### ISSUE THREAD

**Issue by momoe** [alessandrofrancesconi/gimp-plugin-bimp#152]
I would have a lot of use to be able to add a color mode from Menu>Image>Mode>Grayscale since I work with a lot of scanned images that aren't converted to grayscale mode for compresssion. 

Please add this as another Manipulation set option. 

Thanks,
momoe

**Comment by alessandrofrancesconi** [comment]
If your goal is to convert the input images into grayscale first, you can try two ways:
- add a "Color correction -> Convert to grayscale" step
- add a "Other GIMP manipulation -> gimp-image-convert-grayscale" step

Both of them give the same result

**Comment by momoe** [comment]
@alessandrofrancesconi Thank you for that input, and yes while grayscale does clean it up some, I take a further step by reducing the index pallet to just 16 colors to further compress the resulting image file size. This is why I had  originally made this request.
