### ISSUE TITLE
Invert color black/white

### ISSUE THREAD

**Issue by FitoFeat** [alessandrofrancesconi/gimp-plugin-bimp#153]
Hello,
How can i use the "color -> invert " command inside gimp ?
Indeed, i need to switch white color to black and black to white

Thanks for your help
Regards

**Comment by alessandrofrancesconi** [comment]
It's simple, jusst add a "Other GIMP procedure..." step and search for "gimp-invert".
That's the operator that is called when you use "color -> invert" in GIMP.
