### ISSUE TITLE
Install fails fresh install Xubuntu 17.10

### ISSUE THREAD

**Issue by SimonDedman** [alessandrofrancesconi/gimp-plugin-bimp#157]
Hi Alessandro,
I've just installed a new xubuntu 17.10 and am installing BIMP; I got the following issue, I suspect I need some version of gtk, do you know which? Probably gegl-0.3 as well? And please could you add this to the readme for later?
Thanks. Error message was:

$ make
Package gegl-0.3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gegl-0.3.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gegl-0.3', required by 'gimp-2.0', not found
No output from 'pkg-config --cflags gimpui-2.0'
which gimptool-2.0 && which pcre-config && \
gcc -o ./bin/bimp -Wall -O2 -Wno-unused-variable -Wno-pointer-sign -Wno-parentheses src/*.c src/manipulation-gui/*.c   -lpcre -lm -DGIMP_DISABLE_DEPRECATED
/usr/bin/gimptool-2.0
/usr/bin/pcre-config
src/bimp-gui.c:5:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
[about 20 repeats, one for each item]
          ^~~~~~~~~~~
compilation terminated.
Makefile:7: recipe for target 'make' failed
make: *** [make] Error 1

$ sudo apt build-dep bimp
E: Unable to find a source package for bimp

**Comment by alessandrofrancesconi** [comment]
Did you install `libgimp2.0-dev` package before run make?

**Comment by SimonDedman** [comment]
Hi mate, sorry for the slow reply. I did indeed install:

`sudo apt-get install libgimp2.0-dev libpcre3-dev`

per the (very well written - thank you!!) instructions. Just installed `libgtk-3-dev` per [here](https://askubuntu.com/questions/397432/fatal-error-gtk-gtk-h-no-such-file-or-directory-using-make); no change. Could try `sudo apt-get install build-essential gnome-devel` but I'm reluctant to fill my machine with junk just in case it helps, you know?

Thanks!

**Comment by zetheroo** [comment]
I am finding the similar issue on Ubuntu 18.04. 
eb@eab-ux:~/Downloads/gimp-plugin-bimp-master$ sudo make && sudo make install-admin
Package gegl-0.4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gegl-0.4.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gegl-0.4', required by 'gimp-2.0', not found
No output from 'pkg-config --cflags gimpui-2.0'
which gimptool-2.0 && which pcre-config && \
gcc -o ./bin/bimp -Wall -O2 -Wno-unused-variable -Wno-pointer-sign -Wno-parentheses src/*.c src/manipulation-gui/*.c   -lpcre -lm -DGIMP_DISABLE_DEPRECATED
/usr/bin/gimptool-2.0
/usr/bin/pcre-config
src/bimp-gui.c:5:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
src/bimp-manipulations-gui.c:5:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
src/bimp-manipulations.c:6:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
src/bimp-operate.c:6:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
src/bimp-serialize.c:6:10: fatal error: glib.h: No such file or directory
 #include <glib.h>
          ^~~~~~~~
compilation terminated.
src/bimp-utils.c:7:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
src/bimp.c:25:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
src/manipulation-gui/gui-changeformat.c:1:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
src/manipulation-gui/gui-color.c:1:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
src/manipulation-gui/gui-crop.c:1:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
src/manipulation-gui/gui-fliprotate.c:1:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
src/manipulation-gui/gui-rename.c:3:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
src/manipulation-gui/gui-resize.c:1:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
src/manipulation-gui/gui-sharpblur.c:1:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
src/manipulation-gui/gui-userdef.c:1:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
src/manipulation-gui/gui-watermark.c:3:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
Makefile:7: recipe for target 'make' failed
make: *** [make] Error 1

This is after installing libgimp2.0-dev, libpcre3-dev, libgtk-3-dev, gegl

**Comment by alessandrofrancesconi** [comment]
Only `libgimp2.0-dev` and `libpcre3-dev` have to be installed by the user, while all the other packages are dependencies. Have you tried to update the system with `sudo apt-get update` and `sudo apt-get upgrade`?

**Comment by zetheroo** [comment]
Yes, system was and continues to be fully updated.

**Comment by zetheroo** [comment]
I am still having no luck installing on 18.04. Same issue with:
Package gegl-0.4 was not found in the pkg-config search path.

**Comment by zetheroo** [comment]
I completely removed gimp 2.10.4 (which was installed via PPA):

sudo apt-get remove --purge gimp
sudo apt-get remove --purge libgimp2.0-dev libpcre3-dev
sudo apt-get autoremove

Disabled the PPA and reinstalled gimp from the Ubuntu 18.04 repo:

sudo apt-get update && sudo apt-get install gimp

Then reinstalled the needed packages:

sudo apt-get install libgimp2.0-dev libpcre3-dev

And then installing BIMP worked fine. BIMP with GIMP 2.10.4 on Ubuntu 18.04 is a no-go at this time.

**Comment by jrbastien** [comment]
@SimonDedman  and @alessandrofrancesconi , I got the same issue during the make process on Ubuntu 18.04 and Gimp 2.10.8.  It was complaining about Package gegl-0.4 was not found in the pkg-config search path.

I installed lib-gegl-dev and bingo, problem is solved!

I think it is worth adding to the installation instructions.

**Comment by SimonDedman** [comment]
Cheers bastien,

looks like it should be libgegl-dev

Works for me now with latest bimp (2.0), cheers

**Comment by talkinggoat** [comment]
libgegl-dev worked for me, as well on Ubuntu 18 and Gimp 2.10.12
