### ISSUE TITLE
Gimp 2.10 Release Candidate 1.

### ISSUE THREAD

**Issue by nicholasiklim** [alessandrofrancesconi/gimp-plugin-bimp#165]
Dear Alessandro,

Hope Bimp can be updated to work in GIMP 2.10.    At the moment , getting error " The application was unable to start correctly (0xc000007b). Click OK to close the application.

Thanks.

**Comment by alessandrofrancesconi** [comment]
Yes, definitely. Please continue i this thread: https://github.com/alessandrofrancesconi/gimp-plugin-bimp/issues/171
