### ISSUE TITLE
Cannot set parameters for the Distorts->Video filter

### ISSUE THREAD

**Issue by manisoftwartist** [alessandrofrancesconi/gimp-plugin-bimp#168]
In the batch manipulation tool, while using "Other GIMP procedure option", I am unable to use all the parameters that I could otherwise use when directly applying this filter with an open image.
![gimp_issue](https://user-images.githubusercontent.com/707881/39195790-d3f7703e-47e0-11e8-8df1-e1e92ca3421b.png)
While using the Video Filter directly, I have the below additional options
![gimp_issue2](https://user-images.githubusercontent.com/707881/39195836-ee82a1b2-47e0-11e8-9c4e-1c75d7d7a090.png)

**Comment by alessandrofrancesconi** [comment]
Actually, you already have all the parameters you need.
The first parameter "Type of RGB pattern" is a number (I guess) from 0 to 9 that indicates which effect you want to use (again, I guess 0=Staggered, 1=Large Staggered, 2=Striped, ......).
The other two params are to enable (set to 1) or disable (set to 0) the "Additive" and "Rotated" option.

I suggest you to try changing the first parameter from 0 to 9 and see what happen with the Preview button
