### ISSUE TITLE
Bimp doesn´t work with gimp 2.10

### ISSUE THREAD

**Issue by mk00002** [alessandrofrancesconi/gimp-plugin-bimp#171]
![unbenannt](https://user-images.githubusercontent.com/38829369/39403938-bd2366d8-4b87-11e8-998c-410d42f77013.JPG) I installed Gimp 2.10 and the Bimpaddon isn´t visible in the _files menu_ of Gimp.

**Comment by paulhart2** [comment]
I had the same experience. Maybe it needs to be re-compiled for 64 bit operation??

**Comment by maximegti** [comment]
Same problem on Windows 10. Now when I execute Gimp, it show an error and also Bimp can't uninstall,

**Comment by maximegti** [comment]
Thanks @KasimAhmic, it works! ;-)

**Comment by KasimAhmic** [comment]
@nicholasiklim You are correct. It’s actually been around from as early as GIMP 2.4 if I recall correctly. For anyone interested, here is a link to the official post: https://www.gimp.org/tutorials/Basic_Batch/

**Comment by BlackRL** [comment]
Hi and thanks for bimp.

Same problem, Windows 10, Gimp 2.10, Bimp.exe wont start, will you reply in this thread when you fix it so I get notified? Thanks!

**Comment by horusofoz** [comment]
![image](https://user-images.githubusercontent.com/3202339/39660959-e6a19966-5088-11e8-92af-4bb2f3543da4.png)
Windows 10 Pro (Version 1709)
Gimp 2.10.0

**Comment by alessandrofrancesconi** [comment]
Being not under Linux those days, I'm trying to find a place where to download all the needed GIMP 2.10 development binaries for Windows, at least to start with tests on Win32 (the ones needed to run `makewin.bat`). Well... no luck for now. Has anyone managed to download them from somewhere?

The current package I got is for 2.8.x, but I can't remember where I downloaded it in roder to upgrade.

**Comment by mk00002** [comment]
Do you mean the latest developer version? http://ftp.fau.de/gimp/gimp/v2.9/windows/ Gimp 2.9.
https://wiki.gimp.org/wiki/Hacking:Building/Windows

**Comment by alessandrofrancesconi** [comment]
Not actually, I mean the development binaries for GIMP 2.10. It's a package containing the `include` and `lib` folder compiled for Win32, as well as `gimptool-2.0.exe` and other plugin development tools.

**Comment by alessandrofrancesconi** [comment]
I've found this "old" solution, maybe I can use it for 2.10 as well: http://web.archive.org/web/20150906090521/http://registry.gimp.org/node/24883

I'll try soon

**Comment by JohnVV** [comment]
zero issues here on linux

**Comment by rikyxie** [comment]
I saw G'MIC listed both 2.8 and 2.10 version
https://gmic.eu/gimp.shtml

Tried to run all of them in Gimp 2.10:
2.10 win64 version: working
2.8 win64 version: error for could not located dynamic link library dll files
2.8 win32 version: error (0x000007b) same as BIMP

May be they figure out the way to get around it

**Comment by JohnVV** [comment]
until the dev responds .

Have you built Gmic Using MinGW on windows ???
or are you using a very OLD VS 2009 ( or 10,11) 

there are ZERO errors if the build  is using the current gcc or clang

**Comment by rikyxie** [comment]
Didn't build any of them, just downloaded the zip that come with exe and dll files

**Comment by KrasnayaPloshchad** [comment]
If you have used some APIs that no longer compatible in GIMP, see: https://wiki.gimp.org/wiki/Release:2.10_changelog#API_Changes

**Comment by alessandrofrancesconi** [comment]
That's interesting, it could be due to this change:
`  - New API to suppress updates in UI until plug-ins are done
    introducing changes.`

We shall investigate on what APIs are they talking about...

**Comment by BlackRL** [comment]
Good news!

Can confirm! I installed bimp again and it works with Gimp 2.10.2!

Windows 10 x64

**Comment by mk00002** [comment]
I installed Gimp 2.10.2 and it works with bimp again!

**Comment by claudiuconstantin** [comment]
I'm having the same issue, I'm getting this error when starting Gimp 2.10.00:

![image](https://user-images.githubusercontent.com/1537573/40574096-30794974-60d5-11e8-8e65-05d42627dd2d.png)

**Comment by claenn** [comment]
hi there, in the case of an straight forward one and only 64 bit gimp, check 
https://discuss.pixls.us/t/trying-to-get-the-plugin-bimp-into-my-windows-gimp/7847/12

**Comment by claudiuconstantin** [comment]
Tested it, Bimp works with the latest version of Gimp, 2.10.2

**Comment by ysr0** [comment]
> To all, the last commit is my first attempt to address 2.10 compatibility: [b40727a](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/commit/b40727ab339bcdc9dc68b70e7c0831e6a7fe69ef)
> 
> Please test compile & run on your platforms ;)

Tested and it works on my Fedora 29 with Gimp 2.10.6

**Comment by BlackRL** [comment]
Thanks but I can’t find the release for Windows? You only have 1.18?

I don’t have a clue of what to do with the files you posted.

Thanks.

Cumprimentos,
Anselmo

No dia 13/11/2018, às 15:09, ysr0 <notifications@github.com<mailto:notifications@github.com>> escreveu:


To all, the last commit is my first attempt to address 2.10 compatibility: b40727a<https://github.com/alessandrofrancesconi/gimp-plugin-bimp/commit/b40727ab339bcdc9dc68b70e7c0831e6a7fe69ef>

Please test compile & run on your platforms ;)

Tested and it works on my Fedora 29 with Gimp 2.10.6

**Comment by alessandrofrancesconi** [comment]
The Windows build will be generated very soon.


---- BlackRL ha scritto ----

Thanks but I can’t find the release for Windows? You only have 1.18?

I don’t have a clue of what to do with the files you posted.

Thanks.

Cumprimentos,
Anselmo

No dia 13/11/2018, às 15:09, ysr0 <notifications@github.com<mailto:notifications@github.com>> escreveu:


To all, the last commit is my first attempt to address 2.10 compatibility: b40727a<https://github.com/alessandrofrancesconi/gimp-plugin-bimp/commit/b40727ab339bcdc9dc68b70e7c0831e6a7fe69ef>

Please test compile & run on your platforms ;)

Tested and it works on my Fedora 29 with Gimp 2.10.6

**Comment by BlackRL** [comment]
I see, thanks!

**Comment by alessandrofrancesconi** [comment]
Latest version [v2.0](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/releases/tag/v2.0) released also for Win32. Please give it a try!
