### ISSUE TITLE
Build fails with src/manipulation-gui/gui-watermark.c:211:5: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated [-Wdeprecated-declarations]

### ISSUE THREAD

**Issue by felixbecker2** [alessandrofrancesconi/gimp-plugin-bimp#172]
When building `gimp-plugin-bimp` on Arch Linux (using the AUR package http://aur.archlinux.org/packages/gimp-plugin-bimp/), the build fails with:

    [...]
    src/manipulation-gui/gui-watermark.c:211:5: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated [-Wdeprecated-declarations]
         gtk_button_set_image(GTK_BUTTON(button_br), gtk_image_new_from_pixbuf(gdk_pixbuf_from_pixdata(&pixdata_posbr, TRUE, NULL)));
         ^~~~~~~~~~~~~~~~~~~~
    In file included from src/manipulation-gui/../bimp-manipulations.h:5,
                     from src/manipulation-gui/gui-watermark.h:5,
                     from src/manipulation-gui/gui-watermark.c:4:
    /usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119:12: note: declared here
     GdkPixbuf* gdk_pixbuf_from_pixdata (const GdkPixdata *pixdata,
                ^~~~~~~~~~~~~~~~~~~~~~~
    make: *** [Makefile:7: make] Error 1

In the comments section of http://aur.archlinux.org/packages/gimp-plugin-bimp/#comments, there is a note

> Propably best reporting this error upstream. Although this seems to be just a deprecation warning treated as an error. Didn't saw a flag in the Makefile, so dunno where it is set. Maybe it is covered by `-DGIMP_DISABLE_DEPRECATED`

It seems that upstream should change the Makefile.

**Comment by alessandrofrancesconi** [comment]
Latest version [v2.0](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/releases/tag/v2.0) should fix this issue. Please give it a try!
