### ISSUE TITLE
Settings don't save if error happens

### ISSUE THREAD

**Issue by MurKit** [alessandrofrancesconi/gimp-plugin-bimp#174]
I got error "input file without extension", BIMP little window closed immediately,
when I reopen it, Output folder and Manipulation set are back to default.

It would let us work much faster if it didn't default everything.

Edit:
Oh the settings are back to default even on success. Is it something wrong with my installation?

**Comment by alessandrofrancesconi** [comment]
Currently BIMP does not save settings while closing, even on success.
In the meantime, you can save the settings in a file, then load it when reopening BIMP with "Save" and "Load set" menu items.
