### ISSUE TITLE
Trying to install in Manjaro with Gimp 2.10.2 fails

### ISSUE THREAD

**Issue by erik-sk** [alessandrofrancesconi/gimp-plugin-bimp#175]
I was hoping I was going to find something helpful here under the "install fails in Manjaro" post, but they included zero comments. Trying to build this in Manjaro for Gimp 2.10 and it isn't playing nice.

The following is the the result of make:

which gimptool-2.0 && which pcre-config && \
gcc -o ./bin/bimp -Wall -O2 -Wno-unused-variable -Wno-pointer-sign -Wno-parentheses src/*.c src/manipulation-gui/*.c -I/usr/include/gimp-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/uuid -I/usr/include/gegl-0.4 -I/usr/include/json-glib-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/babl-0.1 -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -pthread  -lgimpui-2.0 -lgimpwidgets-2.0 -lgimpmodule-2.0 -lgimp-2.0 -lgimpmath-2.0 -lgimpconfig-2.0 -lgimpcolor-2.0 -lgimpbase-2.0 -lgegl-0.4 -lgegl-npd-0.4 -lm -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0 -ljson-glib-1.0 -lbabl-0.1 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfribidi -lfontconfig -lfreetype   -lpcre -lm -DGIMP_DISABLE_DEPRECATED
/usr/bin/gimptool-2.0
/usr/bin/pcre-config
src/bimp-gui.c: In function ‘add_manipulation_button’:
src/bimp-gui.c:918:5: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated [-Wdeprecated-declarations]
     gtk_button_set_image(GTK_BUTTON(button), gtk_image_new_from_pixbuf(gdk_pixbuf_from_pixdata(man->icon, TRUE, NULL)));
     ^~~~~~~~~~~~~~~~~~~~
In file included from src/bimp-manipulations.h:5,
                 from src/bimp-gui.c:13:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119:12: note: declared here
 GdkPixbuf* gdk_pixbuf_from_pixdata (const GdkPixdata *pixdata,
            ^~~~~~~~~~~~~~~~~~~~~~~
src/bimp-gui.c: In function ‘open_about’:
src/bimp-gui.c:1046:9: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated [-Wdeprecated-declarations]
         "logo", gdk_pixbuf_from_pixdata(&pixdata_bimpicon, FALSE, NULL),
         ^~~~~~
In file included from src/bimp-manipulations.h:5,
                 from src/bimp-gui.c:13:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119:12: note: declared here
 GdkPixbuf* gdk_pixbuf_from_pixdata (const GdkPixdata *pixdata,
            ^~~~~~~~~~~~~~~~~~~~~~~
In file included from src/bimp-manipulations-gui.c:18:
src/manipulation-gui/gui-watermark.h:7: warning: "INPUT_W" redefined
 #define INPUT_W 160
 
In file included from src/bimp-manipulations-gui.c:15:
src/manipulation-gui/gui-color.h:15: note: this is the location of the previous definition
 #define INPUT_W 200
 
src/bimp-manipulations-gui.c: In function ‘bimp_open_editwindow’:
src/bimp-manipulations-gui.c:49:14: warning: assignment to ‘void (*)(void *)’ from incompatible pointer type ‘void (*)(struct manip_resize_set *)’ [-Wincompatible-pointer-types]
         save = &bimp_resize_save;
              ^
src/bimp-manipulations-gui.c:53:14: warning: assignment to ‘void (*)(void *)’ from incompatible pointer type ‘void (*)(struct manip_crop_set *)’ [-Wincompatible-pointer-types]
         save = &bimp_crop_save;
              ^
src/bimp-manipulations-gui.c:57:14: warning: assignment to ‘void (*)(void *)’ from incompatible pointer type ‘void (*)(struct manip_fliprotate_set *)’ [-Wincompatible-pointer-types]
         save = &bimp_fliprotate_save;
              ^
src/bimp-manipulations-gui.c:61:14: warning: assignment to ‘void (*)(void *)’ from incompatible pointer type ‘void (*)(struct manip_color_set *)’ [-Wincompatible-pointer-types]
         save = &bimp_color_save;
              ^
src/bimp-manipulations-gui.c:65:14: warning: assignment to ‘void (*)(void *)’ from incompatible pointer type ‘void (*)(struct manip_sharpblur_set *)’ [-Wincompatible-pointer-types]
         save = &bimp_sharpblur_save;
              ^
src/bimp-manipulations-gui.c:69:14: warning: assignment to ‘void (*)(void *)’ from incompatible pointer type ‘void (*)(struct manip_changeformat_set *)’ [-Wincompatible-pointer-types]
         save = &bimp_changeformat_save;
              ^
src/bimp-manipulations-gui.c:73:14: warning: assignment to ‘void (*)(void *)’ from incompatible pointer type ‘void (*)(struct manip_watermark_set *)’ [-Wincompatible-pointer-types]
         save = &bimp_watermark_save;
              ^
src/bimp-manipulations-gui.c:77:14: warning: assignment to ‘void (*)(void *)’ from incompatible pointer type ‘void (*)(struct manip_rename_set *)’ [-Wincompatible-pointer-types]
         save = &bimp_rename_save;
              ^
src/bimp-manipulations-gui.c:81:14: warning: assignment to ‘void (*)(void *)’ from incompatible pointer type ‘void (*)(struct manip_userdef_set *)’ [-Wincompatible-pointer-types]
         save = &bimp_userdef_save;
              ^
src/bimp-operate.c: In function ‘apply_resize’:
src/bimp-operate.c:563:13: error: ‘GIMP_NORMAL_MODE’ undeclared (first use in this function); did you mean ‘GIMP_REPEAT_NONE’?
             GIMP_NORMAL_MODE
             ^~~~~~~~~~~~~~~~
             GIMP_REPEAT_NONE
src/bimp-operate.c:563:13: note: each undeclared identifier is reported only once for each function it appears in
src/bimp-operate.c:595:37: error: ‘GIMP_BACKGROUND_FILL’ undeclared (first use in this function); did you mean ‘GIMP_CAP_ROUND’?
         gimp_drawable_fill(layerId, GIMP_BACKGROUND_FILL);
                                     ^~~~~~~~~~~~~~~~~~~~
                                     GIMP_CAP_ROUND
src/bimp-operate.c:599:9: warning: ‘gimp_layer_translate’ is deprecated: Use 'gimp_item_transform_translate' instead [-Wdeprecated-declarations]
         gimp_layer_translate(layerId, -abs(view_w - final_w) / 2, -abs(view_h - final_h) / 2);
         ^~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gimp-2.0/libgimp/gimp_pdb_headers.h:66,
                 from /usr/include/gimp-2.0/libgimp/gimp.h:66,
                 from src/bimp-operate.c:7:
/usr/include/gimp-2.0/libgimp/gimplayer_pdb.h:69:24: note: declared here
 gboolean               gimp_layer_translate            (gint32                  layer_ID,
                        ^~~~~~~~~~~~~~~~~~~~
src/bimp-operate.c: In function ‘apply_color’:
src/bimp-operate.c:728:13: warning: ‘gimp_brightness_contrast’ is deprecated: Use 'gimp_drawable_brightness_contrast' instead [-Wdeprecated-declarations]
             success = gimp_brightness_contrast(
             ^~~~~~~
In file included from /usr/include/gimp-2.0/libgimp/gimp_pdb_headers.h:36,
                 from /usr/include/gimp-2.0/libgimp/gimp.h:66,
                 from src/bimp-operate.c:7:
/usr/include/gimp-2.0/libgimp/gimpcolor_pdb.h:36:10: note: declared here
 gboolean gimp_brightness_contrast (gint32                drawable_ID,
          ^~~~~~~~~~~~~~~~~~~~~~~~
src/bimp-operate.c:745:13: warning: ‘gimp_levels_stretch’ is deprecated: Use 'gimp_drawable_levels_stretch' instead [-Wdeprecated-declarations]
             success = gimp_levels_stretch(out->drawable_ids[i]);
             ^~~~~~~
In file included from /usr/include/gimp-2.0/libgimp/gimp_pdb_headers.h:36,
                 from /usr/include/gimp-2.0/libgimp/gimp.h:66,
                 from src/bimp-operate.c:7:
/usr/include/gimp-2.0/libgimp/gimpcolor_pdb.h:50:10: note: declared here
 gboolean gimp_levels_stretch      (gint32                drawable_ID);
          ^~~~~~~~~~~~~~~~~~~
src/bimp-operate.c:771:21: warning: ‘gimp_curves_spline’ is deprecated: Use 'gimp_drawable_curves_spline' instead [-Wdeprecated-declarations]
                     success = gimp_curves_spline(out->drawable_ids[i], GIMP_HISTOGRAM_VALUE, colorcurve_num_points_v, colorcurve_ctr_points_v);
                     ^~~~~~~
In file included from /usr/include/gimp-2.0/libgimp/gimp_pdb_headers.h:36,
                 from /usr/include/gimp-2.0/libgimp/gimp.h:66,
                 from src/bimp-operate.c:7:
/usr/include/gimp-2.0/libgimp/gimpcolor_pdb.h:65:10: note: declared here
 gboolean gimp_curves_spline       (gint32                drawable_ID,
          ^~~~~~~~~~~~~~~~~~
src/bimp-operate.c:775:21: warning: ‘gimp_curves_spline’ is deprecated: Use 'gimp_drawable_curves_spline' instead [-Wdeprecated-declarations]
                     success = gimp_curves_spline(out->drawable_ids[i], GIMP_HISTOGRAM_RED, colorcurve_num_points_r, colorcurve_ctr_points_r);
                     ^~~~~~~
In file included from /usr/include/gimp-2.0/libgimp/gimp_pdb_headers.h:36,
                 from /usr/include/gimp-2.0/libgimp/gimp.h:66,
                 from src/bimp-operate.c:7:
/usr/include/gimp-2.0/libgimp/gimpcolor_pdb.h:65:10: note: declared here
 gboolean gimp_curves_spline       (gint32                drawable_ID,
          ^~~~~~~~~~~~~~~~~~
src/bimp-operate.c:779:21: warning: ‘gimp_curves_spline’ is deprecated: Use 'gimp_drawable_curves_spline' instead [-Wdeprecated-declarations]
                     success = gimp_curves_spline(out->drawable_ids[i], GIMP_HISTOGRAM_GREEN, colorcurve_num_points_g, colorcurve_ctr_points_g);
                     ^~~~~~~
In file included from /usr/include/gimp-2.0/libgimp/gimp_pdb_headers.h:36,
                 from /usr/include/gimp-2.0/libgimp/gimp.h:66,
                 from src/bimp-operate.c:7:
/usr/include/gimp-2.0/libgimp/gimpcolor_pdb.h:65:10: note: declared here
 gboolean gimp_curves_spline       (gint32                drawable_ID,
          ^~~~~~~~~~~~~~~~~~
src/bimp-operate.c:783:21: warning: ‘gimp_curves_spline’ is deprecated: Use 'gimp_drawable_curves_spline' instead [-Wdeprecated-declarations]
                     success = gimp_curves_spline(out->drawable_ids[i], GIMP_HISTOGRAM_BLUE, colorcurve_num_points_b, colorcurve_ctr_points_b);
                     ^~~~~~~
In file included from /usr/include/gimp-2.0/libgimp/gimp_pdb_headers.h:36,
                 from /usr/include/gimp-2.0/libgimp/gimp.h:66,
                 from src/bimp-operate.c:7:
/usr/include/gimp-2.0/libgimp/gimpcolor_pdb.h:65:10: note: declared here
 gboolean gimp_curves_spline       (gint32                drawable_ID,
          ^~~~~~~~~~~~~~~~~~
src/bimp-operate.c:787:21: warning: ‘gimp_curves_spline’ is deprecated: Use 'gimp_drawable_curves_spline' instead [-Wdeprecated-declarations]
                     success = gimp_curves_spline(out->drawable_ids[i], GIMP_HISTOGRAM_ALPHA, colorcurve_num_points_a, colorcurve_ctr_points_a);
                     ^~~~~~~
In file included from /usr/include/gimp-2.0/libgimp/gimp_pdb_headers.h:36,
                 from /usr/include/gimp-2.0/libgimp/gimp.h:66,
                 from src/bimp-operate.c:7:
/usr/include/gimp-2.0/libgimp/gimpcolor_pdb.h:65:10: note: declared here
 gboolean gimp_curves_spline       (gint32                drawable_ID,
          ^~~~~~~~~~~~~~~~~~
src/bimp-operate.c: In function ‘image_save’:
src/bimp-operate.c:1168:17: error: ‘GIMP_FS_DITHER’ undeclared (first use in this function); did you mean ‘GIMP_PDB_ITEM’?
                 GIMP_FS_DITHER,
                 ^~~~~~~~~~~~~~
                 GIMP_PDB_ITEM
src/bimp-operate.c:1169:17: error: ‘GIMP_MAKE_PALETTE’ undeclared (first use in this function); did you mean ‘GIMP_TYPE_PARASITE’?
                 GIMP_MAKE_PALETTE,
                 ^~~~~~~~~~~~~~~~~
                 GIMP_TYPE_PARASITE
src/bimp-operate.c: In function ‘image_save_gif’:
src/bimp-operate.c:1215:9: error: ‘GIMP_FS_DITHER’ undeclared (first use in this function); did you mean ‘GIMP_PDB_ITEM’?
         GIMP_FS_DITHER,
         ^~~~~~~~~~~~~~
         GIMP_PDB_ITEM
src/bimp-operate.c:1216:9: error: ‘GIMP_MAKE_PALETTE’ undeclared (first use in this function); did you mean ‘GIMP_TYPE_PARASITE’?
         GIMP_MAKE_PALETTE,
         ^~~~~~~~~~~~~~~~~
         GIMP_TYPE_PARASITE
In file included from /usr/include/gimp-2.0/libgimpwidgets/gimpwidgets.h:37,
                 from src/manipulation-gui/gui-fliprotate.c:2:
/usr/include/gimp-2.0/libgimpwidgets/gimpcolordisplay.h:97:43: error: unknown type name ‘GeglBuffer’; did you mean ‘GtkTextBuffer’?
                                           GeglBuffer       *buffer,
                                           ^~~~~~~~~~
                                           GtkTextBuffer
/usr/include/gimp-2.0/libgimpwidgets/gimpcolordisplay.h:98:43: error: unknown type name ‘GeglRectangle’; did you mean ‘GdkRectangle’?
                                           GeglRectangle    *area);
                                           ^~~~~~~~~~~~~
                                           GdkRectangle
/usr/include/gimp-2.0/libgimpwidgets/gimpcolordisplay.h:112:52: error: unknown type name ‘GeglBuffer’; did you mean ‘GtkTextBuffer’?
                                                    GeglBuffer       *buffer,
                                                    ^~~~~~~~~~
                                                    GtkTextBuffer
/usr/include/gimp-2.0/libgimpwidgets/gimpcolordisplay.h:113:52: error: unknown type name ‘GeglRectangle’; did you mean ‘GdkRectangle’?
                                                    GeglRectangle    *area);
                                                    ^~~~~~~~~~~~~
                                                    GdkRectangle
In file included from /usr/include/gimp-2.0/libgimpwidgets/gimpwidgets.h:38,
                 from src/manipulation-gui/gui-fliprotate.c:2:
/usr/include/gimp-2.0/libgimpwidgets/gimpcolordisplaystack.h:89:50: error: unknown type name ‘GeglBuffer’; did you mean ‘GtkTextBuffer’?
                                                  GeglBuffer            *buffer,
                                                  ^~~~~~~~~~
                                                  GtkTextBuffer
/usr/include/gimp-2.0/libgimpwidgets/gimpcolordisplaystack.h:90:50: error: unknown type name ‘GeglRectangle’; did you mean ‘GdkRectangle’?
                                                  GeglRectangle         *area);
                                                  ^~~~~~~~~~~~~
                                                  GdkRectangle
In file included from /usr/include/gimp-2.0/libgimpwidgets/gimpwidgets.h:82,
                 from src/manipulation-gui/gui-fliprotate.c:2:
/usr/include/gimp-2.0/libgimpwidgets/gimpwidgetsutils.h:60:61: error: unknown type name ‘Babl’
                                                       const Babl        *src_format,
                                                             ^~~~
/usr/include/gimp-2.0/libgimpwidgets/gimpwidgetsutils.h:61:61: error: unknown type name ‘Babl’
                                                       const Babl        *dest_format);
                                                             ^~~~
src/manipulation-gui/gui-fliprotate.c: In function ‘bimp_fliprotate_gui_new’:
src/manipulation-gui/gui-fliprotate.c:26:5: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated [-Wdeprecated-declarations]
     gtk_button_set_image(GTK_BUTTON(button_flipH), gtk_image_new_from_pixbuf(gdk_pixbuf_from_pixdata(&pixdata_flipH, FALSE, NULL)));
     ^~~~~~~~~~~~~~~~~~~~
In file included from src/manipulation-gui/../bimp-manipulations.h:5,
                 from src/manipulation-gui/gui-fliprotate.h:5,
                 from src/manipulation-gui/gui-fliprotate.c:3:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119:12: note: declared here
 GdkPixbuf* gdk_pixbuf_from_pixdata (const GdkPixdata *pixdata,
            ^~~~~~~~~~~~~~~~~~~~~~~
src/manipulation-gui/gui-fliprotate.c:32:5: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated [-Wdeprecated-declarations]
     gtk_button_set_image(GTK_BUTTON(button_flipV), gtk_image_new_from_pixbuf(gdk_pixbuf_from_pixdata(&pixdata_flipV, FALSE, NULL)));
     ^~~~~~~~~~~~~~~~~~~~
In file included from src/manipulation-gui/../bimp-manipulations.h:5,
                 from src/manipulation-gui/gui-fliprotate.h:5,
                 from src/manipulation-gui/gui-fliprotate.c:3:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119:12: note: declared here
 GdkPixbuf* gdk_pixbuf_from_pixdata (const GdkPixdata *pixdata,
            ^~~~~~~~~~~~~~~~~~~~~~~
src/manipulation-gui/gui-resize.c: In function ‘bimp_resize_save’:
src/manipulation-gui/gui-resize.c:283:40: error: ‘GIMP_INTERPOLATION_LANCZOS’ undeclared (first use in this function); did you mean ‘GIMP_INTERPOLATION_LOHALO’?
         orig_settings->interpolation = GIMP_INTERPOLATION_LANCZOS;
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                        GIMP_INTERPOLATION_LOHALO
src/manipulation-gui/gui-resize.c:283:40: note: each undeclared identifier is reported only once for each function it appears in
src/manipulation-gui/gui-watermark.c: In function ‘bimp_watermark_gui_new’:
src/manipulation-gui/gui-watermark.c:151:5: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated [-Wdeprecated-declarations]
     gtk_button_set_image(GTK_BUTTON(button_tl), gtk_image_new_from_pixbuf(gdk_pixbuf_from_pixdata(&pixdata_postl, TRUE, NULL)));
     ^~~~~~~~~~~~~~~~~~~~
In file included from src/manipulation-gui/../bimp-manipulations.h:5,
                 from src/manipulation-gui/gui-watermark.h:5,
                 from src/manipulation-gui/gui-watermark.c:4:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119:12: note: declared here
 GdkPixbuf* gdk_pixbuf_from_pixdata (const GdkPixdata *pixdata,
            ^~~~~~~~~~~~~~~~~~~~~~~
src/manipulation-gui/gui-watermark.c:158:5: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated [-Wdeprecated-declarations]
     gtk_button_set_image(GTK_BUTTON(button_tc), gtk_image_new_from_pixbuf(gdk_pixbuf_from_pixdata(&pixdata_postc, TRUE, NULL)));
     ^~~~~~~~~~~~~~~~~~~~
In file included from src/manipulation-gui/../bimp-manipulations.h:5,
                 from src/manipulation-gui/gui-watermark.h:5,
                 from src/manipulation-gui/gui-watermark.c:4:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119:12: note: declared here
 GdkPixbuf* gdk_pixbuf_from_pixdata (const GdkPixdata *pixdata,
            ^~~~~~~~~~~~~~~~~~~~~~~
src/manipulation-gui/gui-watermark.c:166:5: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated [-Wdeprecated-declarations]
     gtk_button_set_image(GTK_BUTTON(button_tr), gtk_image_new_from_pixbuf(gdk_pixbuf_from_pixdata(&pixdata_postr, TRUE, NULL)));
     ^~~~~~~~~~~~~~~~~~~~
In file included from src/manipulation-gui/../bimp-manipulations.h:5,
                 from src/manipulation-gui/gui-watermark.h:5,
                 from src/manipulation-gui/gui-watermark.c:4:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119:12: note: declared here
 GdkPixbuf* gdk_pixbuf_from_pixdata (const GdkPixdata *pixdata,
            ^~~~~~~~~~~~~~~~~~~~~~~
src/manipulation-gui/gui-watermark.c:173:5: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated [-Wdeprecated-declarations]
     gtk_button_set_image(GTK_BUTTON(button_cl), gtk_image_new_from_pixbuf(gdk_pixbuf_from_pixdata(&pixdata_poscl, TRUE, NULL)));
     ^~~~~~~~~~~~~~~~~~~~
In file included from src/manipulation-gui/../bimp-manipulations.h:5,
                 from src/manipulation-gui/gui-watermark.h:5,
                 from src/manipulation-gui/gui-watermark.c:4:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119:12: note: declared here
 GdkPixbuf* gdk_pixbuf_from_pixdata (const GdkPixdata *pixdata,
            ^~~~~~~~~~~~~~~~~~~~~~~
src/manipulation-gui/gui-watermark.c:181:5: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated [-Wdeprecated-declarations]
     gtk_button_set_image(GTK_BUTTON(button_cc), gtk_image_new_from_pixbuf(gdk_pixbuf_from_pixdata(&pixdata_poscc, TRUE, NULL)));
     ^~~~~~~~~~~~~~~~~~~~
In file included from src/manipulation-gui/../bimp-manipulations.h:5,
                 from src/manipulation-gui/gui-watermark.h:5,
                 from src/manipulation-gui/gui-watermark.c:4:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119:12: note: declared here
 GdkPixbuf* gdk_pixbuf_from_pixdata (const GdkPixdata *pixdata,
            ^~~~~~~~~~~~~~~~~~~~~~~
src/manipulation-gui/gui-watermark.c:188:5: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated [-Wdeprecated-declarations]
     gtk_button_set_image(GTK_BUTTON(button_cr), gtk_image_new_from_pixbuf(gdk_pixbuf_from_pixdata(&pixdata_poscr, TRUE, NULL)));
     ^~~~~~~~~~~~~~~~~~~~
In file included from src/manipulation-gui/../bimp-manipulations.h:5,
                 from src/manipulation-gui/gui-watermark.h:5,
                 from src/manipulation-gui/gui-watermark.c:4:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119:12: note: declared here
 GdkPixbuf* gdk_pixbuf_from_pixdata (const GdkPixdata *pixdata,
            ^~~~~~~~~~~~~~~~~~~~~~~
src/manipulation-gui/gui-watermark.c:196:5: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated [-Wdeprecated-declarations]
     gtk_button_set_image(GTK_BUTTON(button_bl), gtk_image_new_from_pixbuf(gdk_pixbuf_from_pixdata(&pixdata_posbl, TRUE, NULL)));
     ^~~~~~~~~~~~~~~~~~~~
In file included from src/manipulation-gui/../bimp-manipulations.h:5,
                 from src/manipulation-gui/gui-watermark.h:5,
                 from src/manipulation-gui/gui-watermark.c:4:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119:12: note: declared here
 GdkPixbuf* gdk_pixbuf_from_pixdata (const GdkPixdata *pixdata,
            ^~~~~~~~~~~~~~~~~~~~~~~
src/manipulation-gui/gui-watermark.c:203:5: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated [-Wdeprecated-declarations]
     gtk_button_set_image(GTK_BUTTON(button_bc), gtk_image_new_from_pixbuf(gdk_pixbuf_from_pixdata(&pixdata_posbc, TRUE, NULL)));
     ^~~~~~~~~~~~~~~~~~~~
In file included from src/manipulation-gui/../bimp-manipulations.h:5,
                 from src/manipulation-gui/gui-watermark.h:5,
                 from src/manipulation-gui/gui-watermark.c:4:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119:12: note: declared here
 GdkPixbuf* gdk_pixbuf_from_pixdata (const GdkPixdata *pixdata,
            ^~~~~~~~~~~~~~~~~~~~~~~
src/manipulation-gui/gui-watermark.c:211:5: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated [-Wdeprecated-declarations]
     gtk_button_set_image(GTK_BUTTON(button_br), gtk_image_new_from_pixbuf(gdk_pixbuf_from_pixdata(&pixdata_posbr, TRUE, NULL)));
     ^~~~~~~~~~~~~~~~~~~~
In file included from src/manipulation-gui/../bimp-manipulations.h:5,
                 from src/manipulation-gui/gui-watermark.h:5,
                 from src/manipulation-gui/gui-watermark.c:4:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119:12: note: declared here
 GdkPixbuf* gdk_pixbuf_from_pixdata (const GdkPixdata *pixdata,
            ^~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:7: make] Error 1

**Comment by ChrisJAllan** [comment]
Try applying the following patch:

```diff
diff --git a/Makefile b/Makefile
index 1a7597b..0a22a6a 100644
--- a/Makefile
+++ b/Makefile
@@ -7,3 +7,3 @@ make:
    which gimptool-2.0 && which pcre-config && \
-   gcc -o ./bin/bimp -Wall -O2 -Wno-unused-variable -Wno-pointer-sign -Wno-parentheses src/*.c src/manipulation-gui/*.c $(GIMPARGS) $(PCREARGS) -lm -DGIMP_DISABLE_DEPRECATED
+   gcc -o ./bin/bimp -Wall -O2 -Wno-unused-variable -Wno-pointer-sign -Wno-parentheses src/*.c src/manipulation-gui/*.c $(GIMPARGS) $(PCREARGS) -lm -UGIMP_DISABLE_DEPRECATED

diff --git a/src/manipulation-gui/gui-fliprotate.c b/src/manipulation-gui/gui-fliprotate.c
index ac5638b..e29eda4 100644
--- a/src/manipulation-gui/gui-fliprotate.c
+++ b/src/manipulation-gui/gui-fliprotate.c
@@ -1,2 +1,3 @@
 #include <gtk/gtk.h>
+#include <gegl.h>
 #include <libgimpwidgets/gimpwidgets.h>
```

**Comment by alessandrofrancesconi** [comment]
If it @ChrisJAllan 's solution works, please create a Pull Request

**Comment by TheFeelTrain** [comment]
Adding `#include <gegl.h>` to `src/manipulation-gui/gui-fliprotate.c` fixed the problem for me on Arch Linux.

**Comment by alessandrofrancesconi** [comment]
Latest version [v2.0](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/releases/tag/v2.0) should fix this issue. Please give it a try!
