### ISSUE TITLE
Getting errors with Gimp 2.10.4 on Mac OSX 10.11.6

### ISSUE THREAD

**Issue by windanwaves** [alessandrofrancesconi/gimp-plugin-bimp#176]
[BIMP INSTALL ERROR.pdf](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/files/2369390/BIMP.INSTALL.ERROR.pdf)

Not sure what the issue is, but this is the error that I'm getting. The GIMP app is installed and works properly, but BIMP doesn't seem to want to install for me. :/

Any help is greatly appreciated!

**Comment by alessandrofrancesconi** [comment]
Latest version [v2.0](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/releases/tag/v2.0) should fix this issue. Please give it a try!
