### ISSUE TITLE
HEIC support

### ISSUE THREAD

**Issue by IAmNotImportant** [alessandrofrancesconi/gimp-plugin-bimp#182]
GIMP 2.10 natively supports HEIC, but BIMP does not list them in the _'Select single images...'_ dialog nor after picking directory in _'Select Folders...'_ dialog.

**Comment by alessandrofrancesconi** [comment]
Latest version [v2.0](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/releases/tag/v2.0) should fix this issue. Please give it a try!
