### ISSUE TITLE
Add support to WebP

### ISSUE THREAD

**Issue by alessandrofrancesconi** [alessandrofrancesconi/gimp-plugin-bimp#184]
Add support (open + change format) to WebP

**Comment by Xei5680** [comment]
Hello Alessandro, any update on WebP support?

**Comment by alessandrofrancesconi** [comment]
WebP will be supported from BIMP 2.2

**Comment by d-hardik** [comment]
is it supported now?

**Comment by alessandrofrancesconi** [comment]
Yes it is,from version 2.2

Alessandro

________________________________
