### ISSUE TITLE
Color correction using curve

### ISSUE THREAD

**Issue by rich2005** [alessandrofrancesconi/gimp-plugin-bimp#195]
BIMP v 2.0 Gimp 2.10.8 - Win or Linux

Color Correction procedure - using "Change color curve from settings file" 

Using that setting produces produces blank files.

**Comment by alessandrofrancesconi** [comment]
Can you paste here the contents of the settings file?


---- rich2005 ha scritto ----


BIMP v 2.0 Gimp 2.10.8 - Win or Linux

Color Correction procedure - using "Change color curve from settings file"

Using that setting produces produces blank files.

**Comment by rich2005** [comment]
Works with BIMP 1.18
[SkullCurve2.zip](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/files/2649702/SkullCurve2.zip)
