### ISSUE TITLE
Ubuntu 18.04 - ‘GIMP_LAYER_MODE_NORMAL_LEGACY’ undeclared

### ISSUE THREAD

**Issue by rskaskiw** [alessandrofrancesconi/gimp-plugin-bimp#200]
I cannot get the make file to work. 

> 
> 
> src/bimp-operate.c: In function ‘apply_resize’:
> src/bimp-operate.c:547:13: error: ‘GIMP_LAYER_MODE_NORMAL_LEGACY’ undeclared (first use in this function)
>              GIMP_LAYER_MODE_NORMAL_LEGACY
>              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> src/bimp-operate.c:547:13: note: each undeclared identifier is reported only once for each function it appears in
> src/bimp-operate.c:565:37: error: ‘GIMP_FILL_BACKGROUND’ undeclared (first use in this function); did you mean ‘GIMP_OFFSET_BACKGROUND’?
>          gimp_drawable_fill(layerId, GIMP_FILL_BACKGROUND);
>                                      ^~~~~~~~~~~~~~~~~~~~
>                                      GIMP_OFFSET_BACKGROUND

and other errors as well

Gimp 2.10.8
Bimp 2.0

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by rangerk** [comment]
> $ gimptool-2.0 --version
> 2.8.22

**Comment by alessandrofrancesconi** [comment]
This is not going to work if you have gimptool 2.8.x
You need gimptool 2.10.x


---- Roman ha scritto ----


$ gimptool-2.0 --version
2.8.22

**Comment by rangerk** [comment]
Thank you for the prompt reply!  Trying to figure out how to update it.  I see it not a package, so I can't apt-get purge.

**Comment by GitJer** [comment]
@rangerk Did you find a way to install gimptool 2.10.x? If so: where?

**Comment by rangerk** [comment]
Unfortunately, not yet.  I posted the question here:  
http://gimpforums.com/thread-how-do-i-upgrade-gimptool-2-0-in-ubuntu

**Comment by rich2005** [comment]
No good posting on gimpforums.com, just a spam trap these days.

The default Gimp for 'buntu 18.04 is 2.8.22 for Gimp 2.10.x packages you need the PPA repo. 

https://launchpad.net/~otto-kesselgulasch/+archive/ubuntu/gimp

If you are using a flatpack / snap / appimage these are independent and you need a regular gimp installation.

See: https://www.gimpusers.com/mailmsg.php?91888%40forums.gimpusers.com for a video on compiling and a compiled BIMP2 64 bit linux plugin. This does work in (k)ubuntu 18.04 Gimp 2.10.8

**Comment by ben-lange** [comment]
Same problem here with gimp version:
`gimp --version
GNU Image Manipulation Program version 2.10.8`

OS version from  cat /etc/os-release :
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Full error log attached in the "bimp_error_ubuntu_1804.txt":
[bimp_error_ubuntu_1804.txt](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/files/2923300/bimp_error_ubuntu_1804.txt)

**Comment by rich2005** [comment]
I think you are making it a little too difficult for yourselves.

Download the code

Go into the gimp-plugin-bimp-2.0 folder

run make

Plenty warnings but that is what they are, just warnings (assuming the necessary dev libs are there)

Find the bimp executable in the bin folder.

log & binary attached. 

[log.txt](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/files/2923387/log.txt)

[bimp.zip](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/files/2923388/bimp.zip)

**Comment by rskaskiw** [comment]
I resolved this issue by using a private Gimp repository:
```
sudo add-apt-repository ppa:otto-kesselgulasch/gimp
```

http://ubuntuhandbook.org/index.php/2018/04/how-to-install-gimp-2-10-in-ubuntu-18-04-17-10-via-ppa/
