### ISSUE TITLE
Bimp with Gimp 2.10.4 or 2.8.22  (windows 10, 32 bits) ?

### ISSUE THREAD

**Issue by corbintheone** [alessandrofrancesconi/gimp-plugin-bimp#202]
Hello,

Could anybody tell me if it is possible to have Bimp working in Gimp with one of these two configurations ?

And if it is, what is the procedure, because of course, I tried some on both computers ?

**Comment by K2AAE** [comment]
I just installed 2.10.4 then tried to install bimp, GIMP installed in C:/USER/KEVIN/APPDATA/ROAMING/GIMP/2.10 but bimp is looking for /2.0

**Comment by thegreatestminer** [comment]
The problem is that BIMP is not actually 32bit, it's actually 64bit. The installer is so misleading, it's enraging.

**Comment by alessandrofrancesconi** [comment]
32 bit version is currently available, since 2.4
