### ISSUE TITLE
Plugin Window Resizing Windows 10

### ISSUE THREAD

**Issue by SplinteredSunlight** [alessandrofrancesconi/gimp-plugin-bimp#204]
Window will not resize, minimize or maximize on Windows 10 (Gimp 2.10.8)
![BIMP window](https://user-images.githubusercontent.com/11751018/55038550-6a85d300-4fde-11e9-9aa0-93750c76d310.PNG)

**Comment by JohnBelding** [comment]
I have the same problem.  Has anyone come up with a solution?  BIMP is basically unusable without the resize option.

**Comment by sherifdarwish** [comment]
I have correct size for windows 10 & GIMP 2.10.12

**Comment by SplinteredSunlight** [comment]
I am still experiencing this issue.  Windows 10 Home, Version 1903, fresh install of Gimp and Bimp.  Am I missing something?  Is there a different version of Bimp that I should be installing?
