### ISSUE TITLE
Windows installer triggering antivirus engines again

### ISSUE THREAD

**Issue by MechaLynx** [alessandrofrancesconi/gimp-plugin-bimp#205]
I know you've addressed this before in version 1.18 and it's not your fault but it's a bit of an issue, so could you provide a simple `.zip`/`.7z` archive of the files along with the installer?

Some people like me prefer to just have plugins placed in the directory instead of each of them being separately installed as well. It's not a big issue but it would be helpful, especially when we need to test the files.

I just placed all the contents of the executable installer in a `bimp` directory in my `plug-ins` and it seems to work fine. I'm assuming it's finding `pcre3.dll` by looking in the current directory and it doesn't need it to be in `System32` (which may conflict with perl, though I'm not sure), so if the archive just has all the files in one place so they can be extracted together, it should be enough.

Thanks

edit - forgot to include the [virustotal scan](https://www.virustotal.com/#/file/ad77cb5ac6f51844f273970f311ed4b2b5a3759cafb0f251fde84dd7815e3722/detection)

**Comment by alessandrofrancesconi** [comment]
With v2.2 this should have been fixed
