### ISSUE TITLE
Failing to install on Windows 10 x64

### ISSUE THREAD

**Issue by SabreCat** [alessandrofrancesconi/gimp-plugin-bimp#212]
I'm attempting to install the BIMP plugin on Windows 10 x64, GIMP 2.8.14.

The installer runs without errors, but when I attempt to run GIMP afterward, it complains that libpcre-1.dll was not found.

I went hunting for a fix, but even if I throw libpcre-1.dll into the plug-ins directory, I just get this error instead:

![image](https://user-images.githubusercontent.com/4501321/62987768-05a10d00-be07-11e9-95e8-50765337c9cf.png)

**Comment by MiguelMysko** [comment]
Got the same error, also on Windows 10 x64.
I tried uninstalling, restarting computer, turning of antivirus and reinstalling, but get the same error.

**Comment by SabreCat** [comment]
oh sheesh. I misread that and thought 2.8 was the minimum required version.

Also not sure how I even ended up with version 2.8, given it was a fresh install... well, whatever! Fixed! Thanks @MiguelMysko.
