### ISSUE TITLE
Trijan inside windows installer

### ISSUE THREAD

**Issue by sldprt** [alessandrofrancesconi/gimp-plugin-bimp#217]
Trojan:Win32/Zpevdo.B
This program is dangerous and executes commands from an attacker.

**Comment by lcrumling** [comment]
I get the same warning

**Comment by alessandrofrancesconi** [comment]
This is mostly due to the presence of pcre3.dll in the installer. **It is a false positive** and issue #189 will help to make it safer for antivirus scans.

**Comment by alessandrofrancesconi** [comment]
Also https://nsis.sourceforge.io/NSIS_False_Positives

**Comment by alessandrofrancesconi** [comment]
BIMP 2.2 (now without PCRE) is no more detected by antiviruses: https://www.virustotal.com/gui/file/2a906a3f58317caee2b849b89f92d8e6b89146fb045fe3ae00881844f1409cbf/detection
