### ISSUE TITLE
Selections ignored by BIMP2

### ISSUE THREAD

**Issue by rich2005** [alessandrofrancesconi/gimp-plugin-bimp#221]
Using linux kubuntu 18.04/ Gimp 2.10.12 (and Win10/Gimp 2.10.12)

When using a script 'as-other-gimp-procedure' any selection formed by the script is ignored by BIMP 2

That was not the case with BIMP 1.18

Example attached (zipped). Simple python plugin to make, fade, invert a selection. Find it as other-gimp-procedure 'python_fu_area' Follow by some BIMP function, say a blur or brightness-contrast.

Works with 1.18 which uses the selection but not Bimp 2  which uses the whole image.

[area.py.zip](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/files/3755797/area.py.zip)

**Comment by alessandrofrancesconi** [comment]
BIMP 2 does not support selections, I will work on it in next major releases
