### ISSUE TITLE
Color curves not working 

### ISSUE THREAD

**Issue by JD4x4** [alessandrofrancesconi/gimp-plugin-bimp#225]
Using latest GIMP for Windows 2.10.14, BIMP does not apply saved color correction curves. It will however apply the "canned" brightness/contrast slider values.

**Comment by rich2005** [comment]
It is the format of the saved curve, much changed between Gimp 2.8 and 2.10
see: https://i.imgur.com/nEb85OF.jpg

So while a Gimp 2.8 curve works with both BIMP 1.18 and 2.2 (tested with linux 'buntu Gimp 2.10.14) the new format fails.

**Comment by nicklasb** [comment]
I just tried saving the curve in the old format, and that doesn't seem to work either?

**Comment by rich2005** [comment]
I am now up to Gimp 2.10.20 (linux) and BIMP 2.4, (compiled myself) and with these there is a change from that previous report, 

Both a curve from a Gimp 2.8 and  another from a Gimp 2.10 now work, using BIMP 2.4 

Wonder why not working for you?

**Comment by nicklasb** [comment]
@rich2005, I am running on Windows like @JD4x4 , it might have something to do with that. 
I'll see if there are some logging somewhere.

**Comment by strykeroz** [comment]
Hi I just had a similar experience but now confirm it works fine for me.  The presets saved by Gimp Colors/Levels do not work however also show as completing with 0 errors which is misleading as the output files are the same as the input files.  

The presets saved by Colors/Curves menu option work fine for me (well, is continuing to work - I'm batch updating 208 files as I type this)

Is this the same issue?  An error should be reported I think if the wrong preset type is tried.

Gimp 2.10.20 rev 1

**Comment by nicklasb** [comment]
@strykeroz I am exporting files from Levels using the "Export current settings to file" action. 
Regardless if I use the old or new file formats, the outputs will not change. Neither in the preview. 
It works if I change brightness or contrast in that interface, but not using a file.

Gimp 2.10.20 and BIMP 2.4

**Comment by strykeroz** [comment]
This I confirm does not work.  Instead of COLORS/LEVELS use COLORS/CURVES and export the settings from there.  That file format works.  The information in both types of file is quite different.

As above, the type of file you're trying says it completes with 0 errors, but actually doesn't work at all.  What you are seeing is what I see too.

**Comment by nicklasb** [comment]
@strykeroz Oh, I am sorry, I made a mistake!
I do use COLORS/CURVES, not COLORS/LEVELS, I am afraid.

**Comment by strykeroz** [comment]
That works for me, sorry

**Comment by nicklasb** [comment]
Anybody else have this problem? A solution, perhaps?

**Comment by SaCut** [comment]
Ubuntu 20.04, GIMP 2.10.18, BIMP 2.4, same error. It doesn't load Color→Curves preset files.

**Comment by nicklasb** [comment]
@SaCut  This would suggest that there is some more general problem with that combination of versions.

**Comment by nicklasb** [comment]
@alessandrofrancesconi Several of us seems to have the same problem, I now tried using Ubuntu as  @SaCut did, however I did not succeed. 
Do you know if there is some kind of logging or similar that can be tried? I really need this to work.

**Comment by alessandrofrancesconi** [comment]
Guys, I finally fixed it. Just needed some spare time ;)
