### ISSUE TITLE
error installing on windows

### ISSUE THREAD

**Issue by Pops34** [alessandrofrancesconi/gimp-plugin-bimp#230]
I downloaded gimp-plugin-bimp_win32.exe and executed it. Installation ok. When launching GIMP 2.8.22 (on Windows 8) I had this error message : "Le point d'entrée de procédure gimp_drawable_brightness_contrast est introuvable dans la bibliothèque de liens dynamiques C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\bimp.exe"
Eventually Bimp doesn't appear in GIMP's menu. Don't know what to do...

**Comment by Neonit** [comment]
Seems as if you're missing a DLL. I would try to uninstall GIMP and then install the newer version GIMP 2.10, then retry again.
