### ISSUE TITLE
32bit installer installs 64bit BIMP

### ISSUE THREAD

**Issue by thegreatestminer** [alessandrofrancesconi/gimp-plugin-bimp#236]
Understandably, I'm upset that an installer that explicitly has "32bit" in the filename installs a 64bit executable on a 32bit host.

Please fix.

![image](https://user-images.githubusercontent.com/19188146/84327727-1b2db300-ab4e-11ea-8788-72908c5ab047.png)

**Comment by alessandrofrancesconi** [comment]
You're totally right, this seems to be a long time mistake :)
Please try the attached installer. If ok, I will release it

**Comment by alessandrofrancesconi** [comment]
You're totally right, this seems to be a long time mistake :)
Please try this temporary installer. If ok, I will release it.
https://1drv.ms/u/s!ApL4PYkxwB9_iZBCIB1MPk4GbtgtrA?e=1e3Mz7

**Comment by thegreatestminer** [comment]
It works! Thanks a lot!!
