### ISSUE TITLE
How to install BIMP for the Flathub GIMP

### ISSUE THREAD

**Issue by PrSunflower** [alessandrofrancesconi/gimp-plugin-bimp#238]
Hi! I am used to BIMP on Windows and it's a very useful and user-friendly tool, thanks a lot for that!

## Problem

I am running Debian 10 Buster (64-bit) with GNOME and I tried to install BIMP but it doesn't show up:

![image](https://user-images.githubusercontent.com/59576952/87881296-a6755080-c9f8-11ea-863a-df658e2bcdda.png)

<br>

## Steps taken to install

```
sudo apt update
sudo apt full-upgrade 
sudo apt install libgimp2.0-dev libgegl-dev
cd Downloads/Building_from_source/gimp-plugin-bimp-2.4_32bit/
make -j4
sudo make install-admin
exit
```

<br>

## Other info

When it was making with `make -j4` it showed several **Warnings** and two **Notes** but no errors.

I didn't install GIMP with `apt` as the Debian repositories only have version 2.10.8-2. I have installed GIMP 2.10.20 from Flathub.

<br>

Could someone kindly help me and tell me how to install BIMP on Debian 10 please?

**Comment by alessandrofrancesconi** [comment]
Could you try this instead?

```
cd Downloads/Building_from_source/gimp-plugin-bimp-2.4_32bit/
make -j4
make install
```

Last line is different to yours, it installs in your user directory instead.

**Comment by PrSunflower** [comment]
@alessandrofrancesconi Oh yes this worked well:

![image](https://user-images.githubusercontent.com/59576952/88090140-6bf0ec80-cb8d-11ea-9c7d-59194dec96e7.png)

Thank you very much!

**Comment by PrSunflower** [comment]
In the `README.MD` instead of "**For Ubuntu / Linux Mint**" could you also write "**For Ubuntu / Linux Mint / Debian**" now that we know that it worked for me please?

**Comment by alessandrofrancesconi** [comment]
I've directly changed to "Debian-based (Ubuntu, Linux Mint, ...)"

**Comment by PrSunflower** [comment]
Hi @alessandrofrancesconi ! Just a quick note to say that I was looking for a way to "uninstall" what I've built in order update to BIMP 2.6 and that it was quite easy because you wrote instructions for `make uninstall` to work. 😄

Thanks for that! Do you already have a guide to uninstall BIMP on Debian? If not, could you add it in the Readme please?


<br>

### More info: list of commands I used

```
 2005  git clone https://github.com/alessandrofrancesconi/gimp-plugin-bimp
 2013  cd gimp-plugin-bimp/
 2021  make uninstall
 2022  make clean
 2026  make -j4
 2027  make install
```
