### ISSUE TITLE
Suggested feature: Add saving of manipulation sets

### ISSUE THREAD

**Issue by Pachuquero** [alessandrofrancesconi/gimp-plugin-bimp#241]
Great plugin and many thanks for the wonderful results!

If it was possible to save manipulation sets then it would be possible to quickly process individual images according to needs - particularly if it was possible to drop them onto the BIMP window in GIMP. In other words, why limit BIMP to batch processing of a large number of images - it might as well (with only a few modifications) be also a sort of macro plugin for frequently needed tasks.

A usage scenario is that I have to submit copies of covers, declarations, prescriptions, receipts, etc. all in a digital form. I use my phone to acquire the images but I have to crop, level, sharpen and transform to different sizes which I do repeatedly for each case, many times a month.  Each case is then stored in separate folders for future reference.

Being able to save this sort of processing would be truly helpful and - ideally - if different manipulations can be saved and recalled individually and with ease. The present method of having to configuring from scratch the same procedures every time makes it hardly quicker than doing it directly in GIMP. 

I fully appreciate BIMP's great advantage for users who have a great number of images all requiring the same processing at the same point in time but I would think that many of us also have trickle-tasks each with their own requirement for manipulation.

Cheers!

**Comment by alessandrofrancesconi** [comment]
Hi @Pachuquero . Very useful suggestion! So useful that it is already implemented ;)

I believe the "Save/Load manipulation set" is close to what you wanted:
![image](https://user-images.githubusercontent.com/1595223/90258496-f3f2ab00-de48-11ea-99ec-d8d84c268156.png)

It exports a BIMP configuration file with the current manipulation set, the you can load it again when you need.

**Comment by Pachuquero** [comment]
@alessandrofrancesconi 

_Bump-my-head_ sorry to have missed that. One feature request remains and that would be to be able to directly drop an image directly onto the 'Input files and options' in the BIMP window.

Thanks again and cheers!

**Comment by alessandrofrancesconi** [comment]
The "(1) Single image processing" feature is very hard to implement since it implies "silent" running of BIMP plugin (no GUI). This requires lots of code rewrite. Anyway can be a future enhancement. For now, you can open BIMP and import the **currently opened images** using the submenu for adding files.
