### ISSUE TITLE
Calling error for file-webp-save

### ISSUE THREAD

**Issue by milord65** [alessandrofrancesconi/gimp-plugin-bimp#245]
Hello,

I use BIMP 2.4 with GIMP 2.10.20 (révision 1)

When I want to save images as "file-webp-save" i get the following error message: 

Calling error for procedure 'file-webp-save':
Procedure 'file-webp-save' has been called with a wrong value type for argument 'quality' (#6). Expected gdouble, got GimpInt32.

**Comment by alessandrofrancesconi** [comment]
So you are trying to convert your files into WebP format. Are you using this window?

![image](https://user-images.githubusercontent.com/1595223/93877447-c2d38900-fcd8-11ea-9bdd-18fd95711d77.png)

This is the correct way to do it. I don't see any issue, can you please show me which options did you use?

**Comment by milord65** [comment]
Yes, I'm using this windows but I get the error message 
![erreur-bimp](https://user-images.githubusercontent.com/6603401/93879313-c7e60780-fcdb-11ea-9204-f554ea740823.jpg)

**Comment by alessandrofrancesconi** [comment]
Please write here the values you used

**Comment by milord65** [comment]
Thanks for your quick response and help.
I tried again using the values shown in your screenshot and again got the error message. It's a pity because BIMP is really very useful for transforming groups of images.

**Comment by milord65** [comment]
I uninstalled everything, files and registry for GIMP and BIMP, then reinstalled everything.
Apparently now it works.
Thanks for your help.

**Comment by alessandrofrancesconi** [comment]
"Good" :)
