### ISSUE TITLE
Download flagged as malware

### ISSUE THREAD

**Issue by chumkui** [alessandrofrancesconi/gimp-plugin-bimp#246]
Just downloaded the Windows Installer and Webroot blocked it.  It may well be a false positive, but just letting you know in case its been hacked.
![image](https://user-images.githubusercontent.com/18424420/93775746-b4bf3300-fc1a-11ea-8d1a-b7ac575e95de.png)

**Comment by alessandrofrancesconi** [comment]
Thanks for the report. This is a [common issue](https://nsis.sourceforge.io/NSIS_False_Positives) for programs that uses NSIS installer (BIMP is one of them).
Virus total reports [3 detections over 67](https://www.virustotal.com/gui/file/d117e050539000c0213cfe72567f9faed5136ef7648a39c6fa45d473a836a061/detection), moreover they are from 3 not-so-common antiviruses, compared to others like Avira, AVG, BitDefender .... 

I believe this is enough to say that it is a false positive.

**Comment by chumkui** [comment]
Thanks Alessandro - I'll report this to Webroot as this sot of false positive is an unnecessary waste of everyone's time.

**Comment by alessandrofrancesconi** [comment]
Many, many thanks.

**Comment by chumkui** [comment]
Hi Alessandro

Following my report Webroot have updated their files and all works now.  Just to let you know.

Best regards

Martin
