### ISSUE TITLE
Installing BIMP on Windows 10

### ISSUE THREAD

**Issue by RookmanGold** [alessandrofrancesconi/gimp-plugin-bimp#251]
Hello, I am trying to install BIMP in the plugins folder and it keeps telling me I have chosen the wrong folder... I have tried \GIMP, \GIMP\2.10, \GIMP\2.10\plugins  and I get an error message each time. Hopefully yo can help. Thx

**Comment by RookmanGold** [comment]
UPDATE: it seems it is expecting a lib folder which isnt there...

**Comment by pisourias** [comment]
Hello, ihave the same problem exactly. ty

**Comment by PrSunflower** [comment]
Hi, (I am just a user, not affiliated with BIMP).

When I install BIMP on my Windows 10 (64-bit) everything works fine, the installer installs everything automatically in `C:\Program Files\GIMP 2\\lib\gimp\2.0\plug-ins`.

Try to check your system and download the [corresponding installer](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/releases): **BIMP 2.4** for 64-bit computers and **BIMP 2.4 (32 bit)** for 32-bit computers.

**Comment by RookmanGold** [comment]
Thankyou... I will give it a try...

**Comment by alessandrofrancesconi** [comment]
Solved?
Did you try to reinstall GIMP 2.10, first?

**Comment by RookmanGold** [comment]
Still havnt got round to trying. Will let you know. Thanks for coming back to me,

**Comment by alessandrofrancesconi** [comment]
Closed until new feedback
