### ISSUE TITLE
How can I get gimptool-2.0 on macOs?

### ISSUE THREAD

**Issue by artiumedia** [alessandrofrancesconi/gimp-plugin-bimp#259]
tried to compile the plugin and got this error:
gimptool-2.0 && \ gcc -o ./bin/bimp -Wall -O2 -Wno-unused-variable -Wno-pointer-sign src/*.c src/manipulation-gui/*.c src/images/*.c  -lm -DGIMP_DISABLE_DEPRECATED

I also tried :
$ sudo apt install build-essential
to install gimp dev libs and git client 
$ sudo apt install libgimp2.0-dev git

But Apt not working anymore , any help or suggestion ?

**Comment by scribblemaniac** [comment]
Apt is a package manager for Linux, not macOS. Follow the instructions under "For Mac OSX users" in the readme.

**Comment by alessandrofrancesconi** [comment]
I close this since the instruction in "README -> For Mac OSX users" correctly describes how to get gimptool-2.0 on macOs
