### ISSUE TITLE
Error 127 discoverd on RHEL 8 installation

### ISSUE THREAD

**Issue by jhibbets** [alessandrofrancesconi/gimp-plugin-bimp#265]
Problem - I want to install BIMP so I can do Batch processing; appearently this doesn't come pre-installed on RHEL 8.

`cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.3 (Ootpa)
`

I download the source files from GitHub: https://github.com/alessandrofrancesconi/gimp-plugin-bimp
I've installed gimp-devel and pcre-devel

`sudo dnf install gimp-devel pcre-devel
Updating Subscription Management repositories.
Repository slack is listed more than once in the configuration
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)               1.9 kB/s | 2.8 kB     00:01    
Red Hat Satellite Tools 6.6 for RHEL 8 x86_64 (RPMs)                   1.6 kB/s | 2.1 kB     00:01    
RHEL 8 CSB                                                             1.6 kB/s | 2.1 kB     00:01    
Extra Packages for Enterprise Linux 8 - x86_64                         2.2 kB/s | 2.8 kB     00:01    
Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)                  1.8 kB/s | 2.4 kB     00:01    
Extra Packages for Enterprise Linux Modular 8 - x86_64                 1.9 kB/s | 2.5 kB     00:01    
Package gimp-devel-2:2.8.22-15.module+el8+2760+3d7d61b2.x86_64 is already installed.
Package pcre-devel-8.42-4.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
`

I read the READ.ME and followed the instructions, when I run the make command, I get an error

`[jhibbets@jhibbets gimp-plugin-bimp-2.5]$ make && sudo make install-admin
which gimptool-2.0 && \
gcc -o ./bin/bimp -O2 -I/usr/include/gimp-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libpng16 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -pthread  -Wall -Wno-unused-variable -Wno-pointer-sign -DGIMP_DISABLE_DEPRECATED src/.c src/manipulation-gui/.c src/images/*.c -lgimpui-2.0 -lgimpwidgets-2.0 -lgimpmodule-2.0 -lgimp-2.0 -lgimpmath-2.0 -lgimpconfig-2.0 -lgimpcolor-2.0 -lgimpbase-2.0 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lm
/usr/bin/gimptool-2.0
/bin/sh: line 1: gcc: command not found
make: *** [Makefile:9: make] Error 127`

This is beyond my troubleshooting abilities and I could use some help.

**Comment by scribblemaniac** [comment]
Looks like you don't have gcc installed. Try installing that with dnf and then rebuilding.

**Comment by jhibbets** [comment]
Thank you for the tip (and for not making me feel like an idiot in the process). I got a new laptop in November and so much of what I had installed (or think I have installed) for stuff like this to work, isn't there. I was able to install gcc and the make command then proceeds. However, it fails with a long list of undeclares.
`make: *** [Makefile:9: make] Error 1
`

Full errors attached in case that is useful.
[bimp-make-output.txt](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/files/6025779/bimp-make-output.txt)

I think I'm having compatibility issues. The version of GIMP on my work system is 2.8 and it looks like the latest version of BIMP is designed for GIMP 2.10. I may have to get creative here :(

**Comment by scribblemaniac** [comment]
> I think I'm having compatibility issues. The version of GIMP on my work system is 2.8 and it looks like the latest version of BIMP is designed for GIMP 2.10. I may have to get creative here :(

Yes that would be the cause. BIMP 2.0+ will only work on GIMP 2.10 (and maybe 2.9, but not 2.8). You could downgrade bimp, but then you would be giving up some new features and fixes. If possible try to upgrade gimp. You should be able to build it from source. The flatpak installation will not give you the development files you need.

**Comment by jhibbets** [comment]
A colleague of mine mentioned that I should go to 2.10 via flatpak. I will give that a try and report back. Thank you.

**Comment by jhibbets** [comment]
I decided to just use GIMP 10 on a different system.
