### ISSUE TITLE
BIMP - easy to install on 32/64 bit system

### ISSUE THREAD

**Issue by JMW62** [alessandrofrancesconi/gimp-plugin-bimp#268]
Hi alessandro, I need to batch resize some images and found your program on Google.
I tried the Windows installer, but it informs that it cannot find the GIMP installation folder
on its own. I am using Win10 64 bits and GIMP 2.10.22. I tried locating the installation folder
manually and received the following error notification:

Error: invalid GIMP plugins folder C:\Program Files\GIMP-2.10.22\gimp\lib\gimp\2.0\plug-ins\lib\gimp\2.0\plug-ins

Would appreciate any help! Thanks!

**Comment by alessandrofrancesconi** [comment]
This is a very strange plugins path. 
Can you uninstall+reinstall GIMP entirely without the risk of losing precious data? You should install it in the default location "C:\Program Files\GIMP 2\..."
After that, reinstall BIMP.

**Comment by JMW62** [comment]
Hi Alessandro,

I'm using a customized version of GIMP (i.e. from Partha's Place).
I also thought the path was strange, repeating itself? When I navigate
to the folder either manually or from inside GIMP there doesn't appear
to be any physical folder redundancy? Also, when I installed the exec file
I didn't alter the installation path? But, I will try your suggestion and
see if that works.

Thanks for your help!

**Comment by Gianky63-ita** [comment]
Buongiorno Alessandro,

ho installato Bimp 2.0 sul mio Gimp 2.10.22, ho un PC Windows10 32 bit. Gimp è regolarmente installato su c/Programmi/Gimp 2

Quando apro Gimp purtroppo non trovo l'icona di Bimp nel menù File e quindi non posso utilizzarlo.

ho eseguito l'installazione di Pimp 2.0 con i privilegi di amministratore.

Grazie per la cortese attenzione, attendo suggerimenti.

Giancarlo

**Comment by fong0124** [comment]
I also installed in this path...
(As for your data loss? Delete its plug-in file and install it from there.)
However, this plugin only seems to support 32-bit computers;
After 64-bit installation, it doesn't seem to show up above my feature bar. 

@alessandrofrancesconi
