### ISSUE TITLE
BUG: Broken installation on MacOs

### ISSUE THREAD

**Issue by miceno** [alessandrofrancesconi/gimp-plugin-bimp#270]
Hi! 

I had a problem installing on MacOS Catalina. Folder $HOME/Library/Application Support/GIMP/2.10/plug-ins was not created by the installer, it failed with this message.

I think the problem is the way the folder is created or the issue is related to the whitespace on the "Application Support" part of the path.

I manually created the folder and then I run the install again, and it worked.

Current setup is:
GIMP: 2.10.22
MacOS Catalina.

**Comment by alessandrofrancesconi** [comment]
Thanks for the info, I will enhance the script

**Comment by alessandrofrancesconi** [comment]
I've fixed some installation issues in BIMP v2.6 for MacOS, let me know
