### ISSUE TITLE
bimp not appearing in gimp

### ISSUE THREAD

**Issue by tedastor** [alessandrofrancesconi/gimp-plugin-bimp#279]
I have gimp-2.10 installed. My computer runs on Linux. I have downloaded the zip file for bimp, extracted it to my desktop, run **sudo apt-get install libgimp2.0-dev libgegl-dev**, opened the directory called gimp-plugin-bimp-2.5, run **make && make install**, and reloaded gimp, but bimp doesn't show up in the file tab, or in the plugin browser. Did I miss a step, or is this an issue with bimp?

**Comment by petermoo** [comment]
Gimp 2.10.18. Same problem. Downloaded bimp today and followed the instructions. Cannot find bimp in menu.

`make && make install
which gimptool-2.0 && \
gcc -o ./bin/bimp -O2 -pthread -I/usr/include/gegl-0.4 -I/usr/include/gio-unix-2.0 -I/usr/include/json-glib-1.0 -I/usr/include/babl-0.1 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gimp-2.0 -Wall -Wno-unused-variable -Wno-pointer-sign -DGIMP_DISABLE_DEPRECATED src/*.c src/manipulation-gui/*.c src/images/*.c -lgimpui-2.0 -lgimpwidgets-2.0 -lgimpmodule-2.0 -lgimp-2.0 -lgimpmath-2.0 -lgimpconfig-2.0 -lgimpcolor-2.0 -lgimpbase-2.0 -lgegl-0.4 -lgegl-npd-0.4 -lm -Wl,--export-dynamic -lgmodule-2.0 -pthread -ljson-glib-1.0 -lbabl-0.1 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lfontconfig -lfreetype -lm
/usr/bin/gimptool-2.0
In file included from /usr/include/gtk-2.0/gtk/gtkobject.h:37,
                 from /usr/include/gtk-2.0/gtk/gtkwidget.h:36,
                 from /usr/include/gtk-2.0/gtk/gtkcontainer.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkbin.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkwindow.h:36,
                 from /usr/include/gtk-2.0/gtk/gtkdialog.h:35,
                 from /usr/include/gtk-2.0/gtk/gtkaboutdialog.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:33,
                 from src/bimp-gui.c:5:
/usr/include/gtk-2.0/gtk/gtktypeutils.h:236:1: warning: ‘GTypeDebugFlags’ is deprecated [-Wdeprecated-declarations]
  236 | void            gtk_type_init   (GTypeDebugFlags    debug_flags);
      | ^~~~
`

`/usr/include/gtk-2.0/gtk/gtktooltips.h:73:3: warning: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
   73 |   GTimeVal last_popdown;
      |   ^~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from src/manipulation-gui/gui-watermark.c:3:
/usr/include/glib-2.0/glib/gtypes.h:547:8: note: declared here
  547 | struct _GTimeVal
      |        ^~~~~~~~~
mkdir -p "/home/peter/.config/GIMP/2.10/plug-ins/bimp/"
gimptool-2.0 --install-bin ./bin/bimp
cp './bin/bimp' '/home/peter/.config/GIMP/2.10/plug-ins/bimp/'
cp -Rf ./bimp-locale/ "/home/peter/.config/GIMP/2.10/plug-ins/bimp/"
`

**Comment by petermoo** [comment]
I installed Bimp for my use and it failed to appear. I then installed Bimp for all users and it failed to appear. The following command showed an access error for profile /plug-ins/bimp.
`gimp -i -d -f -s`
I deleted plug-ins/bimp. Bimp appears in Gimp. The following works when not overridden by the local version in my gimp profile.
`make && sudo make install-admin`

**Comment by jpwieg** [comment]
I followed the installation steps for Linux, i'm running Pop OS 21.04, i see BIMP in my .config GIMP 2.10 Plugins folder, but BIMP does not appear in my GIMP File menu. Any suggestions?

Now i'm getting this error message
"Plug-in crashed: "bimp"
(/home/lemur/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/bimp/bimp)
The dying plug-in may have messed up GIMP's internal state. You may want to save your images and restart GIMP to be on the safe side."

Any suggestions?

**Comment by petermoo** [comment]
Update to Bimp not running if installed as user instead of admin.
My Gimp is running with Firejail. Firejail is supposed to allow running of local plugins. I did not find a specific line in the Firejail config to stop the plugin. Might still be relevant.
