### ISSUE TITLE
make: *** [make] Error 1

### ISSUE THREAD

**Issue by arc021t** [alessandrofrancesconi/gimp-plugin-bimp#282]
Hello, 

I was trying to install the plugin and I followed the steps but there seems to be a problem on makefile. 

![Screenshot from 2021-08-10 15-17-05](https://user-images.githubusercontent.com/45868185/128824957-20fc6419-6832-45cf-b79d-1f4564d64da8.png)

![Screenshot from 2021-08-10 15-17-05](https://user-images.githubusercontent.com/45868185/128825011-64b1909f-f231-4f72-9a90-b0b2c5e35fe4.png)

Please let me know what should I do.

**Comment by alessandrofrancesconi** [comment]
You probably have an old version of GIMP (and libgimp2.0-dev package). BIMP supports GIMP >= 2.10.x, if you have GIMP 2.8.x, this should be reason.

If you are not able to upgrade your GIMP version, the most recent version of BIMP you can use on your machine is 1.18: https://github.com/alessandrofrancesconi/gimp-plugin-bimp/releases/tag/v1.18
