### ISSUE TITLE
Virus Total Flagged as malicious

### ISSUE THREAD

**Issue by Captain05** [alessandrofrancesconi/gimp-plugin-bimp#291]
Hi, Windows gave a warning before downloading that the file may be potentially harmful(which never happened before). Anyways I downloaded the .exe installation file and ran it through virustotal and the result was malicious. Can anyone suggest whether it's safe to install. I have downloaded the plugin from this link https://alessandrofrancesconi.it/projects/bimp/

**Comment by alessandrofrancesconi** [comment]
BIMP gets flagged as a false positive, it is not a virus. Please refer to this discussion: https://github.com/alessandrofrancesconi/gimp-plugin-bimp/issues/278

**Comment by Captain05** [comment]
Installed it yesterday after some research. I think the reason why windows is flagging it, is because there is no publisher mentioned. never the less I had an option and reported to Microsoft that it's a safe software. Thanks for the response tough.
