### ISSUE TITLE
Supports Convert the AVIF format. gimp Stable version already supports exporting it.

### ISSUE THREAD

**Issue by 57382** [alessandrofrancesconi/gimp-plugin-bimp#296]
https://avif.io/
Thank you.

**Comment by jhack-jos** [comment]
I have already tested that if you open the image in the editor and then click "Add Image... -> Add all opened images", AVIF files are correctly handled my BIMP. It is now just a matter of adding the AVIF file format to the "Supported Types" list, and BIMP is going to work perfectly with them. With AVIF becoming increasingly popular nowadays, and as easily found as HEIF, it would definitely be a very nice addition.

**Comment by jhack-jos** [comment]
By a light read of the source code it would seem that all changes to be done are in bimp-gui.c.

Inside `static void open_file_chooser(GtkWidget *widget, gpointer data) ` we would need to add something like:
```
    supported[15] = gtk_file_filter_new();
    gtk_file_filter_set_name(supported[15], "AVIF (*.avif)");
    gtk_file_filter_add_pattern (supported[15], "*.[aA][vV][iI][fF]");
    gtk_file_filter_add_pattern (filter_all, "*.[aA][vV][iI][fF]");
```
If we want to keep alphabetical order we would need to add AVIF as element 0 and shift all other declarations adding 1 to their index.

And then in the function `static void add_input_folder_r(char* folder, gboolean with_subdirs) `  inside the if condition at line 319 we would need to add:
```
   g_ascii_strcasecmp(file_extension, ".avif") == 0 ||
```

is there any other change needed I am missing?

**Comment by 57382** [comment]
> By a light read of the source code it would seem that all changes to be done are in bimp-gui.c.
> 
> Inside `static void open_file_chooser(GtkWidget *widget, gpointer data) ` we would need to add something like:
> 
> ```
>     supported[15] = gtk_file_filter_new();
>     gtk_file_filter_set_name(supported[15], "AVIF (*.avif)");
>     gtk_file_filter_add_pattern (supported[15], "*.[aA][vV][iI][fF]");
>     gtk_file_filter_add_pattern (filter_all, "*.[aA][vV][iI][fF]");
> ```
> 
> If we want to keep alphabetical order we would need to add AVIF as element 0 and shift all other declarations adding 1 to their index.
> 
> And then in the function `static void add_input_folder_r(char* folder, gboolean with_subdirs) ` inside the if condition at line 319 we would need to add:
> 
> ```
>    g_ascii_strcasecmp(file_extension, ".avif") == 0 ||
> ```
> 
> is there any other change needed I am missing?

I don't have programming skills.

**Comment by Morxemplum** [comment]
I managed to get most of it done and I'm making a couple tests before making a PR
