### ISSUE TITLE
BIMP Plugin doesn't install on Windows 11

### ISSUE THREAD

**Issue by EnviroGuy** [alessandrofrancesconi/gimp-plugin-bimp#299]
I haven't been able to install BIMP on Windows 11. The installer doesn't allow me to select the following folders for instillation:
C:\Users\<username>\AppData\Roaming\GIMP\2.10\plug-ins
<username>\AppData\Roaming\GIMP\2.10\
<username>\AppData\Roaming\GIMP\

**Comment by wheeOs** [comment]
@EnviroGuy how did you solve this, if I may ask?

**Comment by ghost** [comment]
It seems that the BIMP installer is unable to detect your GIMP installation automatically. This might happen if you have installed GIMP in a different location than the default one. In that case, you need to manually select the folder where GIMP is installed. I found the solution to this problem. It should work if you follow these steps:

Click on OK when you see the message "The installer cannot find GIMP installation by itself. Please click OK and manually select the folder where GIMP is installed."

**You will see a window that says "Browse For Folder." Click on the Browse button and navigate to the folder where you have installed GIMP. For example, if you have installed GIMP in **C:\Users<username>\AppData\Local\Programs\GIMP 2**, then go to that folder and select it.**

Click on OK, and the BIMP installer will proceed with the installation.

It should show: "Welcome to Batch Image Manipulation Plugin for GIMP Setup." Follow the setup instructions to proceed with the installation.

**Comment by gap-bite** [comment]
I just ran into this issue today.
When installing GIMP you will be prompted to install for "current user (recommended)" or for "all users".
You have to install GIMP for all users so that the default install location is in Program Files instead of .../appdata/etc.
For some reason the BIMP installer does not let you direct to the appdata folder.
