### ISSUE TITLE
BIMP for GIMP portable

### ISSUE THREAD

**Issue by kwischan1** [alessandrofrancesconi/gimp-plugin-bimp#309]
Dear Alessandro Francesconi,

thanks al lot for developing BIMP! I liked to use it on my private computer. To use it on a service computer where I don't have administrator rights I just installed GIMP portable. It would be nice if I could add BIMP also to this installation of GIMP.

Sincerly
Ulrich

**Comment by kiwichick888** [comment]
I agree. I would love to use this in GIMP Portable. The BIMP page has a note for Portable users but doesn't say how to install it.

**Comment by kiwichick888** [comment]
> Dear Alessandro Francesconi,
> 
> thanks al lot for developing BIMP! I liked to use it on my private computer. To use it on a service computer where I don't have administrator rights I just installed GIMP portable. It would be nice if I could add BIMP also to this installation of GIMP.
> 
> Sincerly Ulrich

Hi Urlich, I have managed to install it in GIMPPortable v2.10.30.

When the installer is run there will be an error message:
	Installer cannot find GIMP installation folder by itself....
Click OK, then point the installer to install at this location:
	C:\PortableApps\GIMPPortable\App\gimp

**Comment by sheridangis** [comment]
Is there a way to install for portable apps without running the windows installer.
I am in the same boat as 1st person where I do not have admin rights on the box so using portable apps to run GIMP.  To run the BIMP installer you need admin rights, thus I can not run it to point to portable apps.

**Comment by kiwichick888** [comment]
> Is there a way to install for portable apps without running the windows installer. I am in the same boat as 1st person where I do not have admin rights on the box so using portable apps to run GIMP. To run the BIMP installer you need admin rights, thus I can not run it to point to portable apps.

I've just tried and this has worked for me:
Extract the gimp-plugin-bimp installation file (using 7zip, UniExtract).
Regardless of what you end up with, you only need the following:
	folder named bimp-locale
	file named bimp.exe
Move them both to:
	GIMPPortable\App\gimp\lib\gimp\2.0\plug-ins

Good luck!

**Comment by sheridangis** [comment]
kiwichick888, That did exactly what I wanted
Downloaded the windows installer.  
Used 7zip to extract 
-folder named bimp-locale
-file named bimp.exe
extracted them to
-GIMPPortable\App\gimp\lib\gimp\2.0\plug-ins
or the longer path since I have it installed on my hard drive:
D:\PortApps\PortableApps\GIMPPortable\App\gimp\lib\gimp\2.0\plug-ins
Opened Partable Apps and opened Gimp, 
File -> Batch Image Manipulation, is now a menu option and it appears to work.

Thank you!

**Comment by kiwichick888** [comment]
> kiwichick888, That did exactly what I wanted Downloaded the windows installer. Used 7zip to extract -folder named bimp-locale -file named bimp.exe extracted them to -GIMPPortable\App\gimp\lib\gimp\2.0\plug-ins or the longer path since I have it installed on my hard drive: D:\PortApps\PortableApps\GIMPPortable\App\gimp\lib\gimp\2.0\plug-ins Opened Partable Apps and opened Gimp, File -> Batch Image Manipulation, is now a menu option and it appears to work.
> 
> Thank you!

You're very welcome!

**Comment by kwischan1** [comment]
Thanks a lot from me as well! It also worked at my PC.

Sincerly

kwischan

**Comment by kiwichick888** [comment]
> Thanks a lot from me as well! It also worked at my PC. Sincerly kwischan

You're very welcome!
