### ISSUE TITLE
Unable to install on Windows 10

### ISSUE THREAD

**Issue by eqart** [alessandrofrancesconi/gimp-plugin-bimp#315]
When the installer is run I get this message:
Installer cannot find GIMP installation folder by itself....

I have tried directing the installer to every Gimp folder on my computer without success. I made sure to put the Makefile file in the same folder where I tried to install Bimp. 

Any help would be appreciated because I can really use this application. 

Thanks.

![destination folder](https://user-images.githubusercontent.com/89222306/164286198-6a4846bd-f73d-49ca-827b-4e1b028d7f8a.png)
![error message after clicking OK](https://user-images.githubusercontent.com/89222306/164286219-13d013d0-f90a-4b18-a86a-ac11948339c2.png)

**Comment by beppelecce** [comment]
c:\Programmi (x86)\GIMP 2

**Comment by beppelecce** [comment]
Il problema si è presentato dopo che ho installato l'ultima versione di GIMP (2.10.32). In precedenza con 2.10.28 funzionava perfettamente.

**Comment by adymorz** [comment]
My installation of GIMP 2.10.30 is located under `C:\Program Files\GIMP 2\` and the installation worked without troubles.
According to the installer configuration the path should not be an issue: https://github.com/alessandrofrancesconi/gimp-plugin-bimp/blob/665eca9842e7848904fd487e266cbd808e927332/nsis/win32_install.nsi#L74
I have no idea what's going wrong. I hope you get support from someone who knows the project better.

**Comment by beppelecce** [comment]
Thanks for your advice, but the problem no longer occurred when I installed GIMP for all users, not just for me as I had done at first.
