### ISSUE TITLE
App Hang

### ISSUE THREAD

**Issue by JWParenteau** [alessandrofrancesconi/gimp-plugin-bimp#325]
It always crashes for me about half way through the batch. It just goes into app hang. I have to reload the files and say no to overwrite to continue.

How can I get more details?

**Comment by alessandrofrancesconi** [comment]
To reproduce I need to know:
Which operative system do you have?
Which GIMP version?
What manipulations have you added?

**Comment by JWParenteau** [comment]
Windows 10
Gimp 2.10.20 rev 1
I've attached my bimp file as a txt or you can refer to the images:
[Processing.txt](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/files/9223467/Processing.txt)
![1](https://user-images.githubusercontent.com/84361388/181849267-a7828872-f215-40fa-95ee-1aa493f15bd7.png)
![2](https://user-images.githubusercontent.com/84361388/181849272-ea8ce88f-ebca-44a7-b45e-728c2de18a36.png)

**Comment by JWParenteau** [comment]
Also note I am processing the thumbnails from liberto for a digital picture frame, so it's many many files at once:
https://github.com/libretro-thumbnails/libretro-thumbnails
I can only seem to get half way through one folder.

**Comment by JWParenteau** [comment]
I switched advanced properties to force Windows 10 to use my GPU (which now has to be done manually), this wasn't set before and Gimp's "Use Open CL Drivers" was on. With both of these on, Gimp now reported an error after the hang:

Unable to run GimpPdbProgress callback. The corresponding plug-in may have crashed.
Message repeated 5 times.

I'm going to turn of the CL drivers and force windows to use my UHD APU.

**Comment by JWParenteau** [comment]
Old issue, not sure if fixed.
