### ISSUE TITLE
New BIMP import export types

### ISSUE THREAD

**Issue by klaneos** [alessandrofrancesconi/gimp-plugin-bimp#333]
This Plug-in is fantastic!
Is it possible to use BIMP to import a folder of EPS files and export as PDF?
This is a native capability to GIMP (for single file) but doesn't appear to be available in the BIMP plugin?

**Comment by alessandrofrancesconi** [comment]
Hi! Please join [this discussion](https://github.com/alessandrofrancesconi/gimp-plugin-bimp/issues/318) to help understand what is needed when people ask for PDF conversion ;)
