### ISSUE TITLE
question: run own scripts/plugins

### ISSUE THREAD

**Issue by ghost** [alessandrofrancesconi/gimp-plugin-bimp#396]
Hi

Is it possible to run your own gimp  scripts/plugins in bimp?
And if possible, how to do it?
Scripts/plugins  I downloaded and installed in gimp don't appear in bimp

**Comment by alessandrofrancesconi** [comment]
Please share the script. If it is compatible with BIMP, you should find it in the "Other GIMP Procedure..." step.

**Comment by ghost** [comment]
Sorry, it's working perfectly! 
I was confused how BIMP works and now I understand it.
