### ISSUE TITLE
/lib64/libm.so.6: could not read symbols: Invalid operation

### ISSUE THREAD

**Issue by arne-cl** [alessandrofrancesconi/gimp-plugin-bimp#40]
Hi,

I was trying to compile bimp under Fedora 18, but can't get past this error. I tried `export LDFLAGS="$LDFLAGS -lm"` (which is mentioned in several discussions about this error), but it doesn't help either.

`$ make
which gimptool-2.0 && which pcre-config && \
gcc -o ./bin/bimp -Wall -O2 -Wno-unused-variable -Wno-pointer-sign -Wno-parentheses src/*.c src/manipulation-gui/*.c -pthread -I/usr/include/gimp-2.0 -I/usr/include/gtk-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/libpng15 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz   -lgimpui-2.0 -lgimpwidgets-2.0 -lgimpmodule-2.0 -lgimp-2.0 -lgimpmath-2.0 -lgimpconfig-2.0 -lgimpcolor-2.0 -lgimpbase-2.0 -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lglib-2.0    -lpcre -DGIMP_DISABLE_DEPRECATED
/usr/bin/gimptool-2.0
/usr/bin/pcre-config
src/bimp-manipulations-gui.c: In function ‘bimp_open_editwindow’:
src/bimp-manipulations-gui.c:53:8: warning: assignment from incompatible pointer type [enabled by default]
src/bimp-manipulations-gui.c:58:8: warning: assignment from incompatible pointer type [enabled by default]
src/bimp-manipulations-gui.c:63:8: warning: assignment from incompatible pointer type [enabled by default]
src/bimp-manipulations-gui.c:68:8: warning: assignment from incompatible pointer type [enabled by default]
src/bimp-manipulations-gui.c:73:8: warning: assignment from incompatible pointer type [enabled by default]
src/bimp-manipulations-gui.c:78:8: warning: assignment from incompatible pointer type [enabled by default]
src/bimp-manipulations-gui.c:83:8: warning: assignment from incompatible pointer type [enabled by default]
src/bimp-manipulations-gui.c:88:8: warning: assignment from incompatible pointer type [enabled by default]
src/bimp-manipulations-gui.c:93:8: warning: assignment from incompatible pointer type [enabled by default]
/usr/bin/ld: /tmp/ccjJdXom.o: undefined reference to symbol 'roundf@@GLIBC_2.2.5'
/usr/bin/ld: note: 'roundf@@GLIBC_2.2.5' is defined in DSO /lib64/libm.so.6 so try adding it to the linker command line
/lib64/libm.so.6: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make: *** [make] Error 1`

**Comment by voidofcourse** [comment]
I am still getting make error 1 after editing the makefile as suggested above all three ways, adding: 

- /lib/x86_64-linux-gnu/libm.so.6

- /lib/i386-linux-gnu/libm.so.6

- /lib64/libm.so.6

Makefile already has -lm before DGIMP_DISABLE_DEPRECATED

I open the terminal in the Bimp directory, and have tried both `make && make install` and `make && sudo make install-admin` and I get error 1 both ways.

I'm on Ubuntu 12.04 with Crouton on my AcerC720 Chromebook with an Intel 64-bit processor, using Gimp 2.6.

@alessandrofrancesconi you don't need to re-open the issue, I'd just like your input: am I missing something?

**Comment by zhyiyu** [comment]
I encountered with the same error message and adding `-lm` to the Fortran compiler flag works for me.
