### ISSUE TITLE
Padded resize

### ISSUE THREAD

**Issue by vadiOs** [alessandrofrancesconi/gimp-plugin-bimp#62]
Hi! 

First of all, thank you so much for your work on this great plugin.

What stops me from using it in my case, is that I need to resize all images to exact size - 500x500, without breaking proportions, and filling in padding from resized image with background colour (white). Basically image that is 1000x500 should be resized to 500x250 and on the left and right should be added 125px white paddings to fit 500x500.

In Gimp DBP (David's Batch Processor) this feature is called padded resize. But DBP is far from being as good as Bimp. 

Do you plan to add this feature in future?

Thanks!

**Comment by Alveoli** [comment]
+1 this would be very useful! Basically it's the addition of the Canvas Size procedure.

**Comment by alessandrofrancesconi** [comment]
It will be included in 1.16

**Comment by vadiOs** [comment]
Thanks a lot! :)
