### ISSUE TITLE
Tag releases or provide tarballs

### ISSUE THREAD

**Issue by Mailaender** [alessandrofrancesconi/gimp-plugin-bimp#77]
https://github.com/blog/1547-release-your-software

**Comment by Mailaender** [comment]
Updated https://build.opensuse.org/request/show/290355

Windows .exe in Linux tarballs is still pretty ugly. https://github.com/alessandrofrancesconi/gimp-plugin-bimp/issues/76

**Comment by alessandrofrancesconi** [comment]
Yes, I know. In the next versions I'll change the whole directory structure to organize it better
