### ISSUE TITLE
Open folder does not recursively run

### ISSUE THREAD

**Issue by clienthax** [alessandrofrancesconi/gimp-plugin-bimp#78]
i have a sub set of folders that contain images, and also images in the root folder, if i set openfolder to the root folder, the subfolders are ignored.

**Comment by alessandrofrancesconi** [comment]
Hello, have you selected the "Add files from the whole hierarchy" button at the bottom of the folder chooser?

**Comment by clienthax** [comment]
@alessandrofrancesconi Aha completly missed that, thanks
