### ISSUE TITLE
BIMP crashes after version 1.6

### ISSUE THREAD

**Issue by kuroiXiru** [alessandrofrancesconi/gimp-plugin-bimp#79]
I recently updated GIMP, and decided to grab the latest version of BIMP as well. Strangely, BIMP 1.12 works flawlessly on my home PC, but not on my work laptop, where every version past 1.6 crashes. Both PCs have 64 bit Windows 7 (albeit with Bootcamp on the laptop), with fresh GIMP 2.8.14 installs.

(e: To clarify, BIMP versions 1.6 and below work as intended. Versions 1.7 through 1.12 don't work at all.)

Here's the crash description:

  Problem Event Name:	APPCRASH
  Application Name:	bimp.exe
  Application Version:	0.0.0.0
  Application Timestamp:	547645ba
  Fault Module Name:	libglib-2.0-0.dll
  Fault Module Version:	2.40.0.0
  Fault Module Timestamp:	3b243b09
  Exception Code:	c0000005
  Exception Offset:	00050971
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1038
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by alessandrofrancesconi** [comment]
Havo you tried to tried to fully uninstall then reinstall GIMP on your laptop?

**Comment by kuroiXiru** [comment]
Yeah, that was the first thing I tried.

**Comment by alessandrofrancesconi** [comment]
And have you selected "GTK+ Runtime" (or sort of) in the optional components during the installation?

**Comment by kuroiXiru** [comment]
Yep.

**Comment by alessandrofrancesconi** [comment]
Ok, I suggest you to install/update the GTK runtime using the official repository, not the one contained in GIMP: http://sourceforge.net/projects/gtk-win/files/latest/download

Anyway the problem persists. Users should not need to install GTK this way. Let me know if this solves this thing

**Comment by kuroiXiru** [comment]
Nope, sadly. Throws up the same error message.

**Comment by Huspen** [comment]
I can´t Install BIMP to Gimp. Gimp isn´t see. Can you help me? I Install it in the correct Plugins folder on the GImp 2.6 versions.

                                                         Huspen

**Comment by alessandrofrancesconi** [comment]
Closed for lack of information
