### ISSUE TITLE
BIMP wrongly 'corrects' despeckle value - won't allow value over 2

### ISSUE THREAD

**Issue by sstahlman** [alessandrofrancesconi/gimp-plugin-bimp#80]
BiMP 1.13 - Other Gimp procedure - plug-in-despeckle: 

Doesn't allow a Filter Box radius value over 2.  This is odd, considering it helpfully notes the default is 3.  It does allow one to go into negative values quite easily, which the actual despeckle filter within gimp doesn't.

Is there a workaround? 

Using the 'save set' and manually editing the value doesn't work, as it's ignored on load (set back to 2).

**Comment by alessandrofrancesconi** [comment]
Correct, it's a regex issue. I'll work on it.

**Comment by sstahlman** [comment]
Cool, thanks. Also, the gamma, in Levels, is automatically changed from 0.25 to 0.3, which is actually pretty significant (as in, visible pixels in what I'm working on.)

**Comment by alessandrofrancesconi** [comment]
Can you please explain it better, maybe in a new issue? ;) 
Thanks
