### ISSUE TITLE
Crop process starts from center of image

### ISSUE THREAD

**Issue by thief425** [alessandrofrancesconi/gimp-plugin-bimp#81]
When Auto-cropping, users should be able to either A, set a start point for the crop in XY values (or pixel values) such as 0,0, or B) Position/Location (Top Left, Bottom Left, Top Center, Bottom Center, Center, Top Right, etc).  Batch cropping is almost useless in its current form, unless every image has the main subject dead center in the image....which is unlikely to happen with a batch of images.

However, it's much more likely that a set of images might be right weighted or left-weighted (top/bottom, etc) and a user wants to trim the extra space in a direction.  To give an example, I have a batch of images that are similar to polaroids in that they have about 70 pixels of whitespace at the bottom I know the exact size of the images without the whitespace, and if I could crop from the top left position (0,0), then I could set the crop size to 256,330 and batch process roughly 500 images.  Since the crop starts from the center, there is no way for me to get the top of my image, and I still have whitespace at the bottom, as the current image sizes are 256x400.

Any chance this could be fixed, or is the crop function simple enough to fork and customize for myself?

**Comment by alessandrofrancesconi** [comment]
The Crop step can be improved, of course, and your ideas are good.
I suggest you to check what the other batch tools provides when cropping groups of images. Then fork the project and start with some customizations. If you need some "code guidelines", in your case you have to focus on four different areas:

* `manip_crop_set` structure in https://github.com/alessandrofrancesconi/gimp-plugin-bimp/blob/master/src/bimp-manipulations.h#L116 to add the new features as attributes of the crop manipulation step
* `write/read_crop()` in https://github.com/alessandrofrancesconi/gimp-plugin-bimp/blob/master/src/bimp-serialize.c#L228 to make them serializable
* https://github.com/alessandrofrancesconi/gimp-plugin-bimp/blob/master/src/manipulation-gui/gui-crop.c to change the GUI accordingly 
* `apply_crop()` function in https://github.com/alessandrofrancesconi/gimp-plugin-bimp/blob/master/src/bimp-operate.c#L501 to finally apply the new algorithms during process.

**Comment by thief425** [comment]
Thanks. I looked through the source this morning, but couldn't find all of
the methods for the cropping. I'm more familiar with c# than I am c, but I
might be able to do something basic that will either offset the center of
the crop, or will allow a user to enter a starting point for the crop
instead of centering it.

I'd have to write some new methods, probably, because I'm guessing you
don't pass the  image center as a value to the crop.

Do you know where I should be looking, specifically, for the method that
actually crops, or do you have a documentation file that I can navigate
through the various classes and methods?

Thanks,
Shane

**Comment by alessandrofrancesconi** [comment]
"Do you know where I should be looking, specifically, for the method that
actually crops, or do you have a documentation file that I can navigate
through the various classes and methods?"

Look at the last point I wrote. In particular: https://github.com/alessandrofrancesconi/gimp-plugin-bimp/blob/master/src/bimp-operate.c#L541
That's the GIMP function used to crop an image, more info here http://developer.gimp.org/api/2.0/libgimp/libgimp-gimpimage.html#gimp-image-crop

**Comment by thief425** [comment]
Thanks, will do. I was able to go through some of the code, but I'm looking
on my phone while at work, so it may be easier once I get home and put it
on my screen.

**Comment by alessandrofrancesconi** [comment]
definitely yes ;)

**Comment by thief425** [comment]
As I said earlier, I don't know C, but I assume the settings argument that
is passed is an array or key-value pairs. If so, it shouldn't be too hard
to add to the settings array the start coordinates of the crop anchor, and
replace the posX and posY calculation that takes oldImageWidth/2 with new
anchors.

At least from what I can see on my little screen and my limited knowledge
of C.

**Comment by alessandrofrancesconi** [comment]
It's a structure, not an array. See it as a class in C# without methods. Look at the first point of my first comment for its definition.

**Comment by thief425** [comment]
Gotcha, thanks.

**Comment by thief425** [comment]
I finished all of the edits that are necessary, or so it appears, but I
can't get it to compile because I'm missing these references:
#include <unistd.h>
#include <gtk/gtk.h>
#include <libgimp/gimp.h>
#include <libgimpbase/gimpbase.h>
#include <glib.h>
#include <glib/gstdio.h>

I tried to install the GTK+ project to get them, but, honestly, I got lost
in all of it.  I do have the fork I took from your GitHub earlier, so one
alternative is for me to make a pull request, and you can possibly try it
on your end, make sure it isn't buggy, and then merge it if you want.

Or, if you don't mind pointing me to a website that I can comprehend to
figure out how to add the libraries myself, I'm willing to work to do it.
This is just the first time I've even remotely messed with GIMP plugin
writing, and your project is pretty much the deep end, lol.

The coding wasn't too terribly hard, I was able to pick up on the syntax of
the language rather well, I feel, considering I've never seen it before
today.  I little bit of reading documentation, a little bit of studying
other parts of your code that have the same functionality (check box in
resize image), and I was able to get all of the parts together.  I just
can't test them to confirm to you that they work before sending the pull
request back.

Thanks for any more help you can offer.
Shane

**Comment by thief425** [comment]
When you can get around to making an exe file with my changes, let me know if I missed anything, and I'll fix it.  I think I covered every base, but I still haven't really figured out how to add the libraries that are included so I can test it on my end (which I hate).  I'd like to know if it works because I have a crapload of images to edit.

**Comment by alessandrofrancesconi** [comment]
Don't worry, I'll get some free time during the next week and I'll check your pull request :+1:

**Comment by alessandrofrancesconi** [comment]
As you can see, I've included your idea in 1.14, but I've not used exactly your code. Visual Studio had messed up too much things and I cannot test it... so I wrote my own code ;)
Thanks anyway!

**Comment by thief425** [comment]
I appreciate you including it. I did see where VStudio had moved a bunch of
stuff around, and I probably had a few mistakes in there as well because
I'm not very familiar with cpp. But, I do appreciate the credit for the
idea, and hope that I was at least able to contribute enough to make it
easy for you to implement.

( ' _ ' )-b
