### ISSUE TITLE
Remove alpha channel from png

### ISSUE THREAD

**Issue by MOST2K2** [alessandrofrancesconi/gimp-plugin-bimp#84]
Hello how can i remove the alpha channel from png image file?
Problem; Png has no alpha channel, after resize with bimp it has alpha channel.

Regards

**Comment by alessandrofrancesconi** [comment]
Hi, I'm fixing a part of the code that should close this issue too

Thanks
________________________________
Da: MOST2K2<mailto:notifications@github.com>
Inviato: ‎29/‎03/‎2015 13:40
A: alessandrofrancesconi/gimp-plugin-bimp<mailto:gimp-plugin-bimp@noreply.github.com>
Oggetto: [gimp-plugin-bimp] Remove alpha channel from png (#84)

Hello how can i remove the alpha channel from png image file?
Problem; Png has no alpha channel, after resize with bimp it has alpha channel.

Regards

---
Reply to this email directly or view it on GitHub:
https://github.com/alessandrofrancesconi/gimp-plugin-bimp/issues/84
