### ISSUE TITLE
plug-in-exchange does nothing

### ISSUE THREAD

**Issue by fegyi001** [alessandrofrancesconi/gimp-plugin-bimp#87]
I recently found BIMP which seems to be a great tool. However, I tried to use a tool called 'plug-in-exchange' with no success. I hope that maybe you can help me a bit.

My problem is: no matter what parameters I enter, the output picture remains the same. I wish to get the same result when I GIMP's GUI tool for that (Colors >> Map >> Color Exchange). There I add the parameters (see https://www.dropbox.com/s/5nzaiq2lpg86y95/pic01.png?dl=0), the tool runs and gives me the expected results.

When I try to do the same thing in batch using BIMP, I see that the parameters shoud inserted a bit differently (range is not from 0 to 1 but from 0 to 255), but that's not big problem, I extrapolate the values (see https://www.dropbox.com/s/tvqx166dnlct8uf/pic02.png?dl=0). But the output picture is the same as the input, no transformation was being made.
If I use other tools (such as gimp-desaturate, gimp-invert) they work just fine.

Does anyone have a solution for my problem?

**Comment by alessandrofrancesconi** [comment]
I followed the steps and it actually works for me.
Yes, you have to map the values from 0-1 to 0-255 but apart from this the procedure returns a modified image. I tested with the values you entered (https://www.dropbox.com/s/tvqx166dnlct8uf/pic02.png?dl=0)

![cattura](https://cloud.githubusercontent.com/assets/1595223/7649923/c656f178-faf1-11e4-99c3-e73f55a08975.JPG)

**Comment by alessandrofrancesconi** [comment]
Please give us more information about this, or I'll close this issue as "resolved" ;)
