### ISSUE TITLE
Il plugin non dà risultati

### ISSUE THREAD

**Issue by miogithub** [alessandrofrancesconi/gimp-plugin-bimp#89]
Prima di tutto ti chiedo scusa se uso l'italiano ma ho serie difficoltà ad esprimermi in inglese. Il problema è che, nonostante il messaggio "Fine, tutti i file sono stati processati con 0 errori", le operazioni richieste non hanno alcun effetto sui files originali che non vengono modificati. Ho provato prima un resize, poi una conversione in bianco e nero ma niente. Il mio sistema operativo è windows vista 32 bit. L'installazione l'ho effettuata semplicemente copiando i files bimp.exe, pcr3.dll e la cartella bimp-locale nella directory ...gimp/2.0/plug-ins. Ho provato ad avviare gimp con i privilegi di amministratore ma senza successo. Complimenti comunque per l'ottimo lavoro

**Comment by alessandrofrancesconi** [comment]
Ciao e grazie, 
questo è molto strano soprattutto se riguarda azioni "standard" come resize e colore. Hai provato a cambiare la cartella di output ed a ripetere l'operazione?

**Comment by miogithub** [comment]
Grazie per la risposta, ho provato a cambiare la cartella di destinazione e adesso funziona tutto alla perfezione. Poi ho ripetuto l'operazione sulla vecchia cartella e funziona anche li. Problema risolto. Grazie mille e di nuovo complimenti per l'ottimo lavoro.
