### ISSUE TITLE
gimp-rotate doesn't work anymore

### ISSUE THREAD

**Issue by MagdaLa** [alessandrofrancesconi/gimp-plugin-bimp#93]
Hi Alessandro! I really love BIMP and up to now it also worked fine. Since today, however, when I want to rotate an image with gimp-rotate (and also with gimp-item-transform-rotate) I can't put in values for the rotation angle bcse the number turns to zero as soon as I press OK. Do you know what could be the reason for that? Thank you so much!! Best regards, MagdaL

**Comment by alessandrofrancesconi** [comment]
Hello! Could you please expain the steps you made in details? What's the exact moment where the values turn to zero?
I'm assuming you are putting values after you selected "gimp-rotate" from the "Other GIMP procedures" dialog. I'm also assuming that you know that the gimp-rotate procedure takes the angle of rotation in radians, not degrees.
