### ISSUE TITLE
Bimp Make Error under Ubuntu 14.04LTS

### ISSUE THREAD

**Issue by PeterEDz** [alessandrofrancesconi/gimp-plugin-bimp#94]
after having tried to install BIMP using the downloaded files and as per the make script with sudo option I get:

which gimptool-2.0 && which pcre-config && \
	gcc -o ./bin/bimp -Wall -O2 -Wno-unused-variable -Wno-pointer-sign -Wno-parentheses src/*.c src/manipulation-gui/*.c -pthread -I/usr/include/gtk-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/harfbuzz -I/usr/include/gimp-2.0   -lgimpui-2.0 -lgimpwidgets-2.0 -lgimpmodule-2.0 -lgimp-2.0 -lgimpmath-2.0 -lgimpconfig-2.0 -lgimpcolor-2.0 -lgimpbase-2.0 -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfontconfig -lgobject-2.0 -lglib-2.0 -lfreetype    -lpcre -lm -DGIMP_DISABLE_DEPRECATED
/usr/bin/gimptool-2.0
/usr/bin/pcre-config
src/bimp-gui.c: In function ‘bimp_show_error_dialog’:
src/bimp-gui.c:1044:2: warning: format not a string literal and no format arguments [-Wformat-security]
  );
  ^
src/bimp-manipulations-gui.c: In function ‘bimp_open_editwindow’:
src/bimp-manipulations-gui.c:53:8: warning: assignment from incompatible pointer type [enabled by default]
   save = &bimp_resize_save;
        ^
src/bimp-manipulations-gui.c:57:8: warning: assignment from incompatible pointer type [enabled by default]
   save = &bimp_crop_save;
        ^
src/bimp-manipulations-gui.c:61:8: warning: assignment from incompatible pointer type [enabled by default]
   save = &bimp_fliprotate_save;
        ^
src/bimp-manipulations-gui.c:65:8: warning: assignment from incompatible pointer type [enabled by default]
   save = &bimp_color_save;
        ^
src/bimp-manipulations-gui.c:69:8: warning: assignment from incompatible pointer type [enabled by default]
   save = &bimp_sharpblur_save;
        ^
src/bimp-manipulations-gui.c:73:8: warning: assignment from incompatible pointer type [enabled by default]
   save = &bimp_changeformat_save;
        ^
src/bimp-manipulations-gui.c:77:8: warning: assignment from incompatible pointer type [enabled by default]
   save = &bimp_watermark_save;
        ^
src/bimp-manipulations-gui.c:81:8: warning: assignment from incompatible pointer type [enabled by default]
   save = &bimp_rename_save;
        ^
src/bimp-manipulations-gui.c:85:8: warning: assignment from incompatible pointer type [enabled by default]
   save = &bimp_userdef_save;
        ^
src/bimp-utils.c: In function ‘get_bimp_localedir’:
src/bimp-utils.c:171:10: warning: ignoring return value of ‘readlink’, declared with attribute warn_unused_result [-Wunused-result]
  readlink("/proc/self/exe", path, bufsize);
          ^
[sudo] password for peter: 
gimptool-2.0 --install-admin-bin ./bin/bimp
cp ./bin/bimp /usr/lib/gimp/2.0/plug-ins
cp -Rf ./bimp-locale/ /usr/lib/gimp/2.0/plug-ins

I am running 14.04 LTS with updates as of today's date. 

NOTHING appears in Gimp relating to BIMP. 

Thanks for a solution in advance

**Comment by alessandrofrancesconi** [comment]
I dont' see any error in the output, just common warnings. Can you please check if
* after make, the `/bin/bimp` executable actually exists
* `/usr/lib/gimp/2.0/plug-ins` folder actually exists

Anyway I'll try to run this on a Linux distro by myself as soon as possible

**Comment by PeterEDz** [comment]
/bin/bimp **isn't there**, but /usr/lib/gimp/2.0/plug-ins exists and **is** populated

**Comment by alessandrofrancesconi** [comment]
please check if `/bin` is writable by non-root users

**Comment by PeterEDz** [comment]
no it's r-x.

**Comment by alessandrofrancesconi** [comment]
That's the problem. Probably you unzipped the source archive with root privileges. Please make the whole project folder writable for normal users.
