### ISSUE TITLE
Remember last selected folder in file chooser

### ISSUE THREAD

**Issue by alessandrofrancesconi** [alessandrofrancesconi/gimp-plugin-bimp#96]
By mail:

it would be cool if, when you add files from folders, it takes you back to the previous folder, e.g.
> browse > go to full path X/Y/Z > select files A & B
> browse > starts at Z > select files C & D

Otherwise you have to click through the folders again. And it's always really quick to select to top level (home/my documents/whatever) anyway.

**Comment by region51** [comment]
:thumbsup:
