### ISSUE TITLE
Installer can't find GIMP

### ISSUE THREAD

**Issue by JustinEldracher** [alessandrofrancesconi/gimp-plugin-bimp#99]
I have GIMP installed on my windows 8.1 laptop, and I am trying to install your plugin.  However, I get the following error when I try to run the installer:
![image](https://cloud.githubusercontent.com/assets/11478912/10496304/1700e700-728e-11e5-92e5-43075c117eee.png)

What do I need to do so the installer can find GIMP?  I'm quite handy with computers, so I can probably figure out anything you tell me to do. :wink:

**Comment by alessandrofrancesconi** [comment]
Did you install GIMP using the official installer (e.g.: http://download.gimp.org/pub/gimp/v2.8/windows/gimp-2.8.14-setup-1.exe)?

The BIMP installer looks for GIMP registry keys added by the official setup. If you are using a portable version of GIMP this cannot work yet.

**Comment by JustinEldracher** [comment]
I installed the full/official version.

What is the location of the registry key BIMP looks for?  I can add/change it.

**Comment by alessandrofrancesconi** [comment]
It's `Software\Microsoft\Windows\CurrentVersion\Uninstall\GIMP-2_is1`
You can see it here https://github.com/alessandrofrancesconi/gimp-plugin-bimp/blob/master/nsis/win32_install.nsi#L44

**Comment by JustinEldracher** [comment]
Thanks!  It's working now! :grinning:
